<!doctype html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>بلوکام | VoIP سازمانی ساده و قابل اتکا</title>
    <meta name="description" content="بلوکام، سرویس VoIP سازمانی برای مدیریت حرفه‌ای شماره‌ها، داخلی‌ها و تماس‌های کسب‌وکار شما.">
    @fonts
    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="bg-[#fbfaf7] text-[#22221f] antialiased">
    <header class="absolute inset-x-0 top-0 z-20"><nav class="mx-auto flex max-w-6xl items-center justify-between px-5 py-6 lg:px-8"><a href="/" class="flex items-center gap-3" aria-label="بلوکام"><span class="grid size-10 place-items-center rounded-xl bg-[#1f64a8] text-lg font-black text-white shadow-lg shadow-blue-200/50">ب</span><span class="text-xl font-black tracking-tight">بلو<span class="text-[#1f64a8]">کام</span></span></a><div class="flex items-center gap-2 text-sm font-bold"><a href="/login" class="hidden rounded-xl px-4 py-2.5 text-[#5f625e] transition hover:bg-white hover:text-[#1f64a8] sm:inline-flex">ورود</a><a href="/login" class="inline-flex rounded-xl bg-[#1f64a8] px-4 py-2.5 text-white shadow-lg shadow-blue-200/50 transition hover:bg-[#164f87]">شروع رایگان</a></div></nav></header>
    <main>
        <section class="relative isolate overflow-hidden bg-[#eef5f7]" style="background-image:url('{{ asset('assets/images/blucom-hero.png') }}');background-position:center;background-size:cover"><div class="absolute inset-0 -z-10 bg-gradient-to-l from-[#fbfaf7]/95 via-[#fbfaf7]/80 to-[#fbfaf7]/25"></div><div class="mx-auto flex min-h-[720px] max-w-6xl items-center px-5 pb-20 pt-36 lg:px-8"><div class="max-w-2xl"><p class="text-sm font-bold text-[#1f64a8]">تلفن سازمانی، ساده و قابل اتکا</p><h1 class="mt-5 text-5xl font-black leading-[1.18] tracking-tight sm:text-6xl lg:text-7xl">هر تماس مهم است.<br><span class="text-[#1f64a8]">هر پاسخ، حرفه‌ای.</span></h1><p class="mt-7 max-w-xl text-lg leading-9 text-[#5f625e] sm:text-xl">بلوکام، سرویس VoIP سازمانی برای شرکت‌هایی است که می‌خواهند تماس‌های ورودی و خروجی، داخلی‌ها و پاسخ‌گویی تیم‌شان را حرفه‌ای و یکپارچه مدیریت کنند.</p><div class="mt-9 flex flex-col gap-3 sm:flex-row"><a href="/login" class="inline-flex items-center justify-center rounded-xl bg-[#1f64a8] px-7 py-4 font-bold text-white shadow-xl shadow-blue-200/60 transition hover:-translate-y-0.5 hover:bg-[#164f87]">درخواست راهکار VoIP <span class="mr-2">←</span></a><a href="#how" class="inline-flex items-center justify-center rounded-xl border border-[#d9dedb] bg-white/70 px-7 py-4 font-bold text-[#4f5551] backdrop-blur transition hover:border-blue-200 hover:text-[#1f64a8]">امکانات را ببینید</a></div><p class="mt-5 text-sm text-[#858a85]">برای شرکت‌هایی که می‌خواهند پاسخ‌گویی‌شان همیشه یک قدم جلوتر باشد.</p></div></div></section>

        <section class="border-b border-[#e6e5df] bg-[#fbfaf7] px-5 py-24 lg:px-8"><div class="mx-auto max-w-3xl text-center"><p class="text-sm font-bold text-[#c56d42]">مسئله‌ی واقعی</p><h2 class="mt-4 text-3xl font-black leading-tight tracking-tight sm:text-5xl">هیچ مشتری نباید پشت یک تلفن گم شود.</h2><p class="mt-6 text-lg leading-9 text-[#696d68]">وقتی تماس‌ها بین شماره‌های شخصی، تلفن‌های جدا و پاسخ‌های بی‌نظم پخش می‌شوند، تجربه‌ی مشتری آسیب می‌بیند. بلوکام تلفن سازمان شما را به یک سیستم روشن، مرتب و قابل مدیریت تبدیل می‌کند.</p></div></section>

        <section id="how" class="px-5 py-24 lg:px-8"><div class="mx-auto max-w-6xl"><div class="max-w-2xl"><p class="text-sm font-bold text-[#1f64a8]">بلوکام چه می‌کند؟</p><h2 class="mt-4 text-3xl font-black leading-tight tracking-tight sm:text-5xl">ابزار کمتر، وضوح بیشتر</h2><p class="mt-5 text-lg leading-9 text-[#696d68]">یک سیستم تلفنی حرفه‌ای، بدون پیچیدگی‌هایی که معمولاً همراهش می‌آیند.</p></div><div class="mt-14 grid gap-5 md:grid-cols-3">@foreach ([['title'=>'شماره و داخلی سازمانی','body'=>'شماره‌های کاری و داخلی‌های منظم برای اینکه هرکس بداند از کجا و با چه کسی تماس بگیرد.','mark'=>'۰۱'],['title'=>'پاسخ‌گویی هوشمند','body'=>'تماس‌ها را به تیم درست برسانید، صف تماس و مسیر پاسخ‌گویی را متناسب با سازمان‌تان تنظیم کنید.','mark'=>'۰۲'],['title'=>'گزارش روشن از تماس‌ها','body'=>'تصویر دقیق‌تری از تماس‌های پاسخ‌داده‌شده، از دست‌رفته و عملکرد تیم داشته باشید.','mark'=>'۰۳']] as $item)<article class="rounded-2xl border border-[#e3e5e1] bg-white/70 p-7"><span class="text-sm font-black text-[#c56d42]">{{ $item['mark'] }}</span><h3 class="mt-12 text-xl font-black">{{ $item['title'] }}</h3><p class="mt-4 leading-8 text-[#696d68]">{{ $item['body'] }}</p></article>@endforeach</div></div></section>

        <section class="bg-[#e9f0f1] px-5 py-24 lg:px-8"><div class="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p class="text-sm font-bold text-[#1f64a8]">قاعده‌ی ساده‌ی بلوکام</p><h2 class="mt-4 text-3xl font-black leading-tight sm:text-5xl">سیستم تلفنی باید کار را جلو ببرد، نه اینکه خودش تبدیل به کار شود.</h2></div><div class="space-y-7 text-lg leading-9 text-[#59615e]"><p>یک تماس خوب کوتاه، روشن و به‌موقع است. تیم نباید برای مدیریت تلفن سازمان، ساعت‌ها با تنظیمات پیچیده و ابزارهای پراکنده درگیر شود.</p><p>بلوکام پیچیدگی را پشت صحنه نگه می‌دارد تا شما روی مشتری، فروش و کار اصلی‌تان تمرکز کنید.</p><div class="border-r-4 border-[#c56d42] pr-5 text-base font-bold text-[#3e4541]">تلفن را ساده کنید؛ پاسخ‌گویی را بهتر.</div></div></div></section>

        <section class="px-5 py-24 lg:px-8"><div class="mx-auto max-w-6xl"><div class="rounded-3xl bg-[#1f64a8] px-7 py-12 text-white sm:px-14 sm:py-16"><p class="text-sm font-bold text-blue-100">شروعی روشن برای سازمان شما</p><div class="mt-4 flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><h2 class="max-w-2xl text-3xl font-black leading-tight sm:text-5xl">وقت آن است تلفن سازمان‌تان حرفه‌ای‌تر کار کند.</h2><p class="mt-5 max-w-xl leading-8 text-blue-100">یک حساب بسازید یا برای طراحی راهکار VoIP متناسب با سازمان‌تان با ما شروع کنید.</p></div><a href="/login" class="inline-flex shrink-0 rounded-xl bg-white px-7 py-4 font-bold text-[#1f64a8] transition hover:bg-blue-50">شروع همکاری <span class="mr-2">←</span></a></div></div></div></section>
    </main>
    <footer class="border-t border-[#e6e5df] bg-[#fbfaf7] px-5 py-8"><div class="mx-auto flex max-w-6xl flex-col gap-3 text-sm text-[#858a85] sm:flex-row sm:items-center sm:justify-between"><p class="font-bold text-[#22221f]">بلو<span class="text-[#1f64a8]">کام</span></p><p>ارتباط بهتر، کار عمیق‌تر. © {{ now()->year }}</p><a href="/login" class="font-bold transition hover:text-[#1f64a8]">ورود به پنل</a></div></footer>
</body>
</html>
