@extends('layouts.portal')
@section('title', $gateway ? 'ویرایش دروازه SIP' : 'دروازه SIP جدید')
@section('content')
<div class="mx-auto max-w-4xl space-y-5">
    <a href="{{ $returnDraft ? route('admin.setup.show', $returnDraft) : route('sip-gateways.index') }}" class="text-sm font-bold text-blue-700">← {{ $returnDraft ? 'بازگشت به راه‌اندازی سریع' : 'بازگشت به دروازه‌ها' }}</a>
    <div><h1 class="text-2xl font-black">{{ $gateway ? 'ویرایش دروازه '.$gateway->name : 'دروازه SIP جدید' }}</h1><p class="mt-2 text-sm text-slate-600">پروفایل external و کانتکست public در سرور قفل شده‌اند. رمز ذخیره‌شده نمایش داده نمی‌شود.</p></div>
    @if ($errors->any())<div role="alert" class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><ul class="list-disc space-y-1 pr-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    @unless (config('voip.gateway_xml_enabled'))<div class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">XML-CURL دروازه فعال نیست؛ ذخیره این فرم فعلاً اتصال زنده را تغییر نمی‌دهد.</div>@endunless
    <form method="POST" action="{{ $gateway ? route('sip-gateways.update', $gateway) : route('sip-gateways.store') }}" class="space-y-5">
        @csrf @if($gateway) @method('PUT') @endif
        @if($returnDraft)<input type="hidden" name="setup_id" value="{{ $returnDraft->id }}">@endif
        <section class="panel space-y-5 p-5 sm:p-7">
            <div><h2 class="font-bold">مالک و اتصال</h2><p class="mt-1 text-xs text-slate-500">مالک فقط هنگام ساخت انتخاب می‌شود.</p></div>
            <div class="grid gap-4 sm:grid-cols-2">
                @unless($gateway)<label class="text-sm font-bold">مالک اتصال<select name="tenant_id" class="mt-2 w-full rounded-xl border border-slate-200 bg-white p-3 font-normal"><option value="">زیرساخت بلوکام</option>@foreach($tenants as $tenant)<option value="{{ $tenant->id }}" @selected(old('tenant_id', $returnDraft?->tenant_id) == $tenant->id)>{{ $tenant->name }}</option>@endforeach</select></label>@else<div class="text-sm"><span class="block font-bold">مالک اتصال</span><span class="mt-2 block rounded-xl bg-slate-50 p-3">{{ $gateway->tenant?->name ?? 'زیرساخت بلوکام' }}</span></div>@endunless
                <label class="text-sm font-bold">نام دروازه<input name="name" value="{{ old('name', $gateway?->name) }}" required pattern="[a-zA-Z0-9_-]+" dir="ltr" class="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal"></label>
                <label class="text-sm font-bold">هاست<input name="host" value="{{ old('host', $gateway?->host) }}" required dir="ltr" class="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal"></label>
                <label class="text-sm font-bold">پورت<input name="port" type="number" min="1" max="65535" value="{{ old('port', $gateway?->port ?? 5060) }}" required dir="ltr" class="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal"></label>
                <label class="text-sm font-bold">ترنسپورت<select name="transport" class="mt-2 w-full rounded-xl border border-slate-200 bg-white p-3 font-normal">@foreach(['udp','tcp','tls'] as $transport)<option value="{{ $transport }}" @selected(old('transport', $gateway?->transport ?? 'udp') === $transport)>{{ strtoupper($transport) }}</option>@endforeach</select></label>
            </div>
        </section>
        <section class="panel space-y-5 p-5 sm:p-7"><div><h2 class="font-bold">احراز هویت ارائه‌دهنده</h2><p class="mt-1 text-xs text-slate-500">اگر ارائه‌دهنده ثبت SIP نمی‌خواهد، می‌توانید این اطلاعات را خالی بگذارید.</p></div><div class="grid gap-4 sm:grid-cols-2">
            <label class="text-sm font-bold">نام کاربری<input name="username" value="{{ old('username', $gateway?->username) }}" dir="ltr" class="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal"></label>
            <label class="text-sm font-bold">نام کاربری احراز هویت (اختیاری)<input name="auth_username" value="{{ old('auth_username', $gateway?->auth_username) }}" dir="ltr" class="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal"></label>
            <label class="text-sm font-bold">Realm (اختیاری)<input name="realm" value="{{ old('realm', $gateway?->realm) }}" dir="ltr" class="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal"></label>
            <label class="text-sm font-bold">رمز عبور<input name="password" type="password" autocomplete="new-password" dir="ltr" class="mt-2 w-full rounded-xl border border-slate-200 p-3 font-normal"><span class="mt-1 block text-xs font-normal text-slate-500">{{ $gateway ? 'خالی بگذارید تا رمز فعلی حفظ شود.' : 'فقط برای ثبت SIP لازم است.' }}</span></label>
        </div></section>
        <section class="panel space-y-5 p-5 sm:p-7"><div><h2 class="font-bold">رفتار و مجوز تماس</h2><p class="mt-1 text-xs text-slate-500">این موارد تنظیمات هستند و نشان‌دهنده وضعیت لحظه‌ای ثبت نزد ارائه‌دهنده نیستند.</p></div>
            <fieldset class="space-y-2"><legend class="text-sm font-bold">ثبت SIP نزد ارائه‌دهنده</legend><label class="block rounded-xl border border-slate-200 p-3 text-sm"><input type="radio" name="register" value="0" @checked((string) old('register', (int) ($gateway?->register ?? false)) === '0')> بدون ثبت SIP</label><label class="block rounded-xl border border-slate-200 p-3 text-sm"><input type="radio" name="register" value="1" @checked((string) old('register', (int) ($gateway?->register ?? false)) === '1')> با نام کاربری و رمز عبور ثبت شود</label></fieldset>
            <div class="grid gap-3 sm:grid-cols-2"><label class="block rounded-xl border border-slate-200 p-4 text-sm"><input type="hidden" name="enabled" value="0"><input type="checkbox" name="enabled" value="1" @checked(old('enabled', $gateway?->enabled ?? true))> <strong>دروازه در تنظیمات فعال باشد</strong><span class="mt-1 block text-xs text-slate-500">غیرفعال‌سازی می‌تواند تماس‌های وابسته را متوقف کند.</span></label><label class="block rounded-xl border border-slate-200 p-4 text-sm"><input type="hidden" name="approved_for_outbound" value="0"><input type="checkbox" name="approved_for_outbound" value="1" @checked(old('approved_for_outbound', $gateway?->approved_for_outbound ?? false))> <strong>برای تماس خروجی مجاز باشد</strong><span class="mt-1 block text-xs text-slate-500">فقط مسیرهای مجاز می‌توانند از آن استفاده کنند.</span></label></div>
        </section>
        @if($gateway && ($gateway->sip_numbers_count || $gateway->outbound_routes_count))<p class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">این دروازه به {{ $gateway->sip_numbers_count }} شماره و {{ $gateway->outbound_routes_count }} مسیر خروجی وابسته است. پیش از تغییر اتصال یا غیرفعال‌سازی، اثر آن بر تماس‌ها را بررسی کنید.</p>@endif
        <div class="sticky bottom-0 flex items-center justify-between gap-4 rounded-xl border border-slate-200 bg-white/95 p-4 shadow-lg backdrop-blur"><a href="{{ route('sip-gateways.index') }}" class="text-sm font-bold text-slate-600">انصراف</a><button class="rounded-xl bg-blue-600 px-6 py-3 text-sm font-bold text-white">{{ $gateway ? 'ذخیره تغییرات' : 'ثبت دروازه' }}</button></div>
    </form>
    @if($gateway)<form method="POST" action="{{ route('sip-gateways.destroy', $gateway) }}" onsubmit="return confirm('دروازه حذف شود؟ این کار قابل بازگشت نیست.')">@csrf @method('DELETE')<button @disabled($gateway->sip_numbers_count || $gateway->outbound_routes_count) class="text-xs font-bold text-red-700 disabled:cursor-not-allowed disabled:text-slate-400">حذف دروازه</button>@if($gateway->sip_numbers_count || $gateway->outbound_routes_count)<span class="mr-2 text-xs text-slate-500">ابتدا شماره‌ها و مسیرهای وابسته را جدا کنید.</span>@endif</form>@endif
</div>
@endsection
