@extends('layouts.portal')
@section('title', 'شماره‌های DID')
@section('content')
<div class="mb-6 flex flex-wrap items-start justify-between gap-3"><div><h1 class="text-2xl font-black">شماره‌های DID</h1><p class="mt-2 text-sm text-slate-500">اتصال، پاسخ‌گو، ساعت کاری و تماس خروجی هر شماره را در فضای مدیریت آن تنظیم کنید.</p></div><a href="{{ route('admin.setup.index') }}" class="rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white">+ راه‌اندازی سریع خط</a></div>
@if(session('status'))<div class="mb-4 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">{{ session('status') }}</div>@endif
@if($errors->any())<div role="alert" class="mb-4 rounded-xl bg-red-50 p-4 text-sm text-red-800">{{ $errors->first() }}</div>@endif
<form method="GET" class="panel mb-5 flex flex-wrap gap-3 p-4"><input name="q" value="{{ request('q') }}" placeholder="شماره یا برچسب" aria-label="جست‌وجوی شماره" class="rounded-lg border border-slate-200 p-2"><select name="tenant_id" aria-label="مالک" class="rounded-lg border border-slate-200 p-2"><option value="">همه مالک‌ها</option>@foreach($tenants as $tenant)<option value="{{ $tenant->id }}" @selected(request('tenant_id') == $tenant->id)>{{ $tenant->name }}</option>@endforeach</select><select name="gateway_id" aria-label="اتصال" class="rounded-lg border border-slate-200 p-2"><option value="">همه اتصال‌ها</option>@foreach($gateways as $gateway)<option value="{{ $gateway->id }}" @selected(request('gateway_id') == $gateway->id)>{{ $gateway->name }}</option>@endforeach</select><select name="filter" aria-label="وضعیت پیکربندی" class="rounded-lg border border-slate-200 p-2">@foreach(['' => 'همه شماره‌ها', 'missing_route' => 'بدون مسیر ورودی', 'scheduled' => 'زمان‌بندی‌شده', 'disabled' => 'غیرفعال'] as $value => $label)<option value="{{ $value }}" @selected(request('filter', '') === $value)>{{ $label }}</option>@endforeach</select><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm text-white">فیلتر</button><a href="{{ route('admin.sip-numbers.index') }}" class="p-2 text-sm text-slate-500">پاک کردن</a></form>
<div class="panel overflow-x-auto"><table class="w-full min-w-[900px] text-right text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4">شماره / مالک</th><th class="p-4">اتصال</th><th class="p-4">پاسخ‌گوی ورودی</th><th class="p-4">زمان‌بندی</th><th class="p-4">خروجی</th><th class="p-4">پیکربندی</th><th class="p-4">عملیات</th></tr></thead><tbody>
@forelse($numbers as $number)<tr class="border-t border-slate-100"><td class="p-4"><a href="{{ route('admin.sip-numbers.setup', $number) }}" class="font-bold text-blue-700" dir="ltr">{{ $number->normalized_number }}</a><small class="mt-1 block text-slate-500">{{ $number->tenant?->name }} · {{ $number->label ?: 'بدون برچسب' }}</small></td><td class="p-4">{{ $number->providerGateway?->name ?? 'تعیین نشده' }}</td><td class="p-4">{{ $number->inboundRoute?->destinationLabel() ?? 'تعیین نشده' }}</td><td class="p-4"><a href="{{ route('admin.sip-numbers.setup', ['sip_number' => $number->id, 'tab' => 'inbound']) }}" class="text-blue-700">{{ $number->inboundRoute?->schedule ? 'ساعت کاری و تعطیلی‌ها' : 'همیشه' }}</a></td><td class="p-4">{{ $number->outbound_enabled ? $number->active_outbound_routes_count.' داخلی' : 'غیرفعال' }}</td><td class="p-4"><span class="text-xs {{ ! $number->enabled ? 'text-slate-500' : ($number->inboundRoute && $number->provider_gateway_id ? 'text-emerald-700' : 'text-amber-800') }}">{{ ! $number->enabled ? 'غیرفعال' : ($number->status === 'pending' ? 'در انتظار تأیید' : ($number->inboundRoute && $number->provider_gateway_id ? 'مسیر ذخیره شده' : 'نیازمند تکمیل')) }}</span></td><td class="p-4"><a href="{{ route('admin.sip-numbers.setup', $number) }}" class="whitespace-nowrap font-bold text-blue-700">مدیریت شماره ←</a></td></tr>@empty<tr><td colspan="7" class="p-6 text-slate-500">شماره‌ای با این فیلتر پیدا نشد.</td></tr>@endforelse
</tbody></table><div class="p-4">{{ $numbers->links() }}</div></div>
<details id="new-number" class="panel mt-6 scroll-mt-24 p-5" @if($errors->any() && old('number')) open @endif><summary class="cursor-pointer font-bold">افزودن فقط شماره DID برای بلوکام</summary><p class="mt-2 text-xs text-slate-500">برای راه‌اندازی کامل یا انتخاب مالک مشتری، از راه‌اندازی سریع استفاده کنید.</p><form method="POST" action="{{ route('admin.sip-numbers.store') }}" class="mt-5 grid gap-4 sm:grid-cols-2">@csrf<label class="text-sm">شماره<input name="number" value="{{ old('number') }}" required dir="ltr" class="mt-1 w-full rounded-lg border border-slate-200 p-3"></label><label class="text-sm">برچسب<input name="label" value="{{ old('label') }}" class="mt-1 w-full rounded-lg border border-slate-200 p-3"></label><div class="flex flex-wrap gap-4 text-sm">@foreach(['enabled' => 'فعال', 'inbound_enabled' => 'ورودی', 'outbound_enabled' => 'خروجی'] as $key => $label)<label><input type="hidden" name="{{ $key }}" value="0"><input type="checkbox" name="{{ $key }}" value="1" @checked(old($key, true))> {{ $label }}</label>@endforeach</div><div><button class="rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white">ثبت شماره</button></div></form></details>
@endsection
