@extends('layouts.portal')
@section('title', 'مدیریت شماره')
@section('content')
@if($number->inventory_state === 'assigned' && $number->current_assignment_id)
<a href="{{ route('admin.numbers.cancellation', $number) }}" class="mb-4 inline-block rounded-xl border border-red-200 p-3 text-sm font-bold text-red-700">لغو سرویس و آزادسازی شماره</a>
@endif

@php
    $route = $number->inboundRoute;
    $scope = $tenant->system_key === 'blucom' ? [] : ['tenant_id' => $tenant->id];
    $completeSteps = collect([$numberReady, $providerReady, $numberReady && $number->inbound_enabled && $answerReady, ! $number->outbound_enabled || $outboundReady])->filter()->count();
@endphp
<div class="mx-auto max-w-5xl space-y-6">
    <div class="flex flex-wrap justify-between gap-4"><div><a href="{{ route('admin.sip-numbers.index') }}" class="text-xs font-bold text-blue-700">← همه شماره‌ها</a><h1 class="mt-3 text-2xl font-black" dir="ltr">{{ $number->normalized_number }}</h1><p class="mt-2 text-sm text-slate-500">مالک: {{ $tenant->name }} · {{ $number->label ?: 'بدون برچسب' }} · {{ $number->statusLabel() }}</p></div><div class="space-y-3 text-left"><span class="block rounded-full bg-blue-50 px-4 py-2 text-sm font-bold text-blue-800">{{ $completeSteps }} از ۴ مرحله پیکربندی</span><a href="{{ route('admin.setup.index', ['tenant_id' => $tenant->id]) }}" class="inline-block text-sm font-bold text-blue-700">راه‌اندازی سریع خط ←</a></div></div>
    @if(session('status'))<div role="status" class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{{ session('status') }}</div>@endif
    @if($errors->any())<div role="alert" class="rounded-xl bg-red-50 p-4 text-sm text-red-800">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
    @if(session('phone_credentials'))
        <section class="rounded-xl border border-amber-200 bg-amber-50 p-5"><h2 class="font-bold">مشخصات تلفن جدید · فقط این بار نمایش داده می‌شود</h2><p class="mt-2 text-sm">رمز را در جای امن نگه دارید و به پاسخ‌گو تحویل دهید.</p><dl class="mt-4 grid gap-3 text-sm sm:grid-cols-4">@foreach(session('phone_credentials') as $key => $value)<div><dt>{{ ['extension' => 'داخلی', 'password' => 'رمز', 'host' => 'سرور', 'port' => 'پورت'][$key] }}</dt><dd class="mt-1 select-all break-all font-mono" dir="ltr">{{ $value }}</dd></div>@endforeach</dl></section>
    @endif
    <nav class="flex gap-2 overflow-x-auto rounded-xl border border-slate-200 bg-white p-2" aria-label="مدیریت شماره"><a href="{{ route('recordings.numbers.edit', $number) }}" class="whitespace-nowrap rounded-lg px-4 py-3 text-sm font-bold text-blue-700">ضبط و نگهداری</a>@foreach(['overview' => 'نمای کلی', 'inbound' => 'ورودی و ساعت کاری', 'outbound' => 'تماس خروجی', 'settings' => 'تنظیمات'] as $key => $label)<a href="{{ route('admin.sip-numbers.setup', ['sip_number' => $number->id, 'tab' => $key]) }}" @if($tab === $key) aria-current="page" @endif class="whitespace-nowrap rounded-lg px-4 py-3 text-sm font-bold {{ $tab === $key ? 'bg-blue-600 text-white' : 'text-slate-600 hover:bg-slate-50' }}">{{ $label }}</a>@endforeach</nav>
    @if($tab === 'overview')
        <div class="grid gap-4 sm:grid-cols-3">
            <section class="panel p-5"><h2 class="text-sm font-bold text-slate-500">اتصال ارائه‌دهنده</h2><p class="mt-3 font-bold">{{ $number->providerGateway?->name ?? 'تعیین نشده' }}</p><p class="mt-2 text-xs {{ $providerReady ? 'text-emerald-700' : 'text-amber-700' }}">{{ $providerReady ? 'پیکربندی اتصال فعال است' : 'اتصال نیازمند تنظیم یا تأیید است' }}</p><a href="{{ route('admin.sip-numbers.setup', ['sip_number' => $number->id, 'tab' => 'settings']) }}" class="mt-4 block text-sm font-bold text-blue-700">تنظیم اتصال ←</a></section>
            <section class="panel p-5"><h2 class="text-sm font-bold text-slate-500">تماس ورودی</h2><p class="mt-3 font-bold">{{ $route?->destinationLabel() ?? 'پاسخ‌گو تعیین نشده' }}</p><p class="mt-2 text-xs text-slate-500">{{ $route?->schedule ? 'طبق ساعت کاری و تعطیلی‌ها' : 'بدون زمان‌بندی' }}</p><a href="{{ route('admin.sip-numbers.inbound', $number) }}" class="mt-4 block text-sm font-bold text-blue-700">{{ $route ? 'ویرایش پاسخ‌گو و ساعت کاری' : 'تعیین پاسخ‌گو و ساعت کاری' }} ←</a></section>
            <section class="panel p-5"><h2 class="text-sm font-bold text-slate-500">تماس خروجی</h2><p class="mt-3 font-bold">{{ $outboundRoutes->where('enabled', true)->count() }} داخلی مجاز</p><p class="mt-2 text-xs text-slate-500">شماره‌نمایش: <span dir="ltr">{{ $number->normalized_number }}</span></p><a href="{{ route('outbound-routes.index', ['sip_number_id' => $number->id] + $scope) }}" class="mt-4 block text-sm font-bold text-blue-700">مدیریت مسیرهای خروجی ←</a></section>
        </div>
        <section class="panel p-6"><h2 class="font-black">مسیر تماس این شماره</h2><div class="mt-4 space-y-3 text-sm"><p>در {{ $route?->schedule ? 'ساعت‌های کاری' : 'تمام ساعت‌ها' }} ← <strong>{{ $route?->destinationLabel() ?? 'تعیین نشده' }}</strong></p>@if($route?->schedule)<p>خارج از ساعت کاری و تعطیلی‌ها ← <strong>{{ $route->closedDestinationLabel() }}</strong></p>@endif<p>خروجی ← داخلی‌های مجاز از طریق <strong>{{ $number->providerGateway?->name ?? 'اتصال تعیین نشده' }}</strong> با شماره‌نمایش همین DID</p></div><div class="mt-5 flex flex-wrap gap-4 text-xs font-bold text-blue-700"><a href="{{ route('inbound-routes.index', ['sip_number_id' => $number->id] + $scope) }}">همه مسیرهای ورودی</a><a href="{{ route('sip-extensions.index') }}">مدیریت داخلی‌ها</a><a href="{{ route('ivr-menus.index', ['number_id' => $number->id]) }}">مدیریت منوی تماس</a></div></section>
        <section class="panel p-6"><h2 class="font-black">آزمایش واقعی</h2><p class="mt-2 text-sm text-slate-600">نتیجه تماس واقعی هنوز در این صفحه ثبت یا تأیید نمی‌شود.</p><ol class="mt-4 list-decimal space-y-2 pr-5 text-sm text-slate-700"><li>ثبت SIP اتصال و تلفن را بررسی کنید.</li><li>تماس ورودی بگیرید؛ مقصد ساعات باز و بسته را آزمایش کنید.</li><li>از داخلی مجاز تماس خروجی بگیرید و شماره‌نمایش را بررسی کنید.</li></ol><a href="{{ route('calls.index') }}" class="mt-4 inline-block text-sm font-bold text-blue-700">مشاهده تاریخچه تماس‌ها ←</a></section>
    @elseif($tab === 'inbound')
        <section class="panel space-y-4 p-6"><div class="flex flex-wrap justify-between gap-3"><h2 class="font-black">تماس ورودی و ساعت کاری</h2><a href="{{ route('admin.sip-numbers.inbound', $number) }}" class="rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white">ویرایش مقصد و زمان‌بندی</a></div><p class="text-sm">در ساعات باز: <strong>{{ $route?->destinationLabel() ?? 'تعیین نشده' }}</strong></p>@include('shared.schedule-summary', ['schedule' => $route?->schedule])@if($route?->schedule)<p class="text-sm">ساعات بسته: <strong>{{ $route->closedDestinationLabel() }}</strong></p><p class="text-xs text-slate-500">اکنون طبق زمان‌بندی: {{ $openNow ? 'ساعات باز' : 'ساعات بسته' }}</p>@endif<p class="text-xs {{ $number->inbound_enabled && $route?->enabled ? 'text-emerald-700' : 'text-amber-800' }}">{{ $number->inbound_enabled && $route?->enabled ? 'مسیر ورودی فعال است' : 'شماره یا مسیر ورودی غیرفعال یا ناقص است' }}</p></section>
        @if($route)<section class="panel p-6"><h2 class="font-bold">پیش‌نمایش مسیر برای تاریخ و ساعت</h2><p class="mt-2 text-xs text-slate-500">پیکربندی ذخیره‌شده را بررسی می‌کند؛ تماس آزمایشی برقرار نمی‌کند. زمان به وقت {{ $route->schedule['timezone'] ?? 'Asia/Tehran' }} است.</p><form method="POST" action="{{ route('admin.sip-numbers.preview', $number) }}" class="mt-4 flex flex-wrap gap-3">@csrf<label class="text-sm">تاریخ و ساعت میلادی<input type="datetime-local" name="at" required dir="ltr" class="mr-2 rounded-lg border border-slate-200 p-2"></label><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm text-white">بررسی مسیر</button></form>@if(session('schedule_preview'))<div role="status" class="mt-4 rounded-xl bg-blue-50 p-4 text-sm"><p dir="ltr">{{ session('schedule_preview.at') }}</p><p class="mt-2">{{ session('schedule_preview.reason') }} ← {{ session('schedule_preview.destination') }}</p></div>@endif</section>@endif
    @elseif($tab === 'outbound')
        <section class="panel p-6"><h2 class="font-black">داخلی‌های مجاز و شماره‌نمایش</h2><p class="mt-2 text-sm text-slate-500">هر مسیر باید از شماره همین مالک و دروازه مجاز استفاده کند.</p><div class="mt-4 divide-y divide-slate-100">@forelse($outboundRoutes as $outbound)<div class="flex flex-wrap justify-between gap-3 py-4 text-sm"><span>{{ $outbound->sipExtension?->display_name }} · <span dir="ltr">{{ $outbound->sipExtension?->extension }}</span> ← {{ $outbound->gateway?->name }}</span><a href="{{ route('outbound-routes.edit', $outbound) }}" class="font-bold text-blue-700">{{ $outbound->enabled ? 'فعال · ویرایش' : 'غیرفعال · ویرایش' }}</a></div>@empty<p class="py-4 text-sm text-slate-500">مسیر خروجی تنظیم نشده است.</p>@endforelse</div><a href="{{ route('outbound-routes.create', ['sip_number_id' => $number->id] + $scope) }}" class="mt-4 inline-block rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white">+ مسیر خروجی جدید</a>@unless($number->outbound_enabled)<p class="mt-4 text-sm text-amber-800">تماس خروجی شماره غیرفعال است. در تنظیمات آن را فعال کنید.</p>@endunless</section>
    @else
        <section class="panel p-6"><h2 class="font-black">مشخصات و دسترسی شماره</h2><p class="mt-2 text-xs text-slate-500">فعال بودن شماره، پیش‌نیاز تماس ورودی و خروجی است. غیرفعال‌سازی ممکن است تماس‌های وابسته را متوقف کند.</p><form method="POST" action="{{ route('admin.sip-numbers.update', $number) }}" class="mt-5 space-y-4">@csrf @method('PUT')<label class="block text-sm font-bold">برچسب<input name="label" value="{{ old('label', $number->label) }}" class="mt-2 w-full rounded-lg border border-slate-200 p-3"></label><div class="grid gap-3 text-sm sm:grid-cols-2"><label class="rounded-xl border border-slate-200 p-4 sm:col-span-2"><input type="hidden" name="enabled" value="0"><input type="checkbox" name="enabled" value="1" @checked(old('enabled', $number->enabled))> <strong>این شماره در سرویس فعال باشد</strong><span class="mt-1 block text-xs text-slate-500">خاموش کردن آن، ورودی و خروجی را با وجود تنظیمات ذخیره‌شده متوقف می‌کند.</span></label><label class="rounded-xl border border-slate-200 p-4"><input type="hidden" name="inbound_enabled" value="0"><input type="checkbox" name="inbound_enabled" value="1" @checked(old('inbound_enabled', $number->inbound_enabled))> <strong>تماس ورودی دریافت شود</strong><span class="mt-1 block text-xs text-slate-500">به مقصد و زمان‌بندی ذخیره‌شده هدایت می‌شود.</span></label><label class="rounded-xl border border-slate-200 p-4"><input type="hidden" name="outbound_enabled" value="0"><input type="checkbox" name="outbound_enabled" value="1" @checked(old('outbound_enabled', $number->outbound_enabled))> <strong>برای تماس خروجی مجاز باشد</strong><span class="mt-1 block text-xs text-slate-500">داخلی‌ها همچنان به مسیر خروجی مجاز نیاز دارند.</span></label></div><button class="rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white">ذخیره تنظیمات</button></form></section>
        <section class="panel p-6"><h2 class="font-black">اتصال ارائه‌دهنده</h2><form method="POST" action="{{ route('admin.sip-numbers.gateway', $number) }}" class="mt-4 flex flex-wrap gap-3">@csrf @method('PUT')<select name="provider_gateway_id" aria-label="دروازه این شماره" required class="min-w-64 flex-1 rounded-lg border border-slate-200 bg-white p-3"><option value="">انتخاب اتصال</option>@foreach($gateways as $gateway)<option value="{{ $gateway->id }}" @selected($number->provider_gateway_id === $gateway->id)>{{ $gateway->name }} · {{ $gateway->host }}</option>@endforeach</select><button class="rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white">ذخیره اتصال</button></form><a href="{{ route('sip-gateways.index') }}" class="mt-4 block text-sm font-bold text-blue-700">مدیریت دروازه‌ها ←</a></section>
        <section class="panel p-6"><h2 class="font-black">حذف شماره</h2><p class="mt-2 text-sm text-slate-500">برای حذف، ابتدا مسیرهای ورودی و خروجی وابسته را حذف کنید.</p><form method="POST" action="{{ route('admin.sip-numbers.destroy', $number) }}" onsubmit="return confirm('شماره حذف شود؟')" class="mt-4">@csrf @method('DELETE')<button class="rounded-xl border border-red-200 px-5 py-3 text-sm font-bold text-red-700">حذف شماره</button></form></section>
    @endif
</div>
@endsection
