@extends('layouts.portal')
@section('title', 'راه‌اندازی سریع خط')
@section('content')
@php
    $labels = [1 => 'مالک', 2 => 'اتصال', 3 => 'شماره', 4 => 'پاسخ‌گو و ساعت کاری', 5 => 'خروجی', 6 => 'بررسی و پایان'];
    $gateway = $gateways->firstWhere('id', $data['gateway_id'] ?? null);
@endphp
<div class="mx-auto max-w-4xl space-y-5">
    <div class="flex flex-wrap justify-between gap-3"><div><a href="{{ route('admin.setup.index') }}" class="text-xs font-bold text-blue-700">← همه پیش‌نویس‌ها</a><h1 class="mt-3 text-2xl font-black">راه‌اندازی سریع خط</h1><p class="mt-2 text-sm text-slate-600">مالک: <strong>{{ $tenant->name }}</strong> · پیش‌نویس #{{ $draft->id }}</p></div><span class="self-start rounded-full bg-blue-50 px-4 py-2 text-xs font-bold text-blue-700">تا پایان بررسی، تنظیمات تماس تغییر نمی‌کند</span></div>
    <nav aria-label="مراحل راه‌اندازی" class="flex gap-2 overflow-x-auto">
        @foreach($labels as $index => $label)
            @if($index > 1 && $index <= $draft->step)
                <a href="{{ route('admin.setup.show', ['setup' => $draft->id, 'step' => $index]) }}" @if($step === $index) aria-current="step" @endif class="whitespace-nowrap rounded-xl px-3 py-3 text-xs font-bold {{ $step === $index ? 'bg-blue-600 text-white' : 'bg-white text-slate-600' }}">{{ $index }}. {{ $label }}</a>
            @else
                <span class="whitespace-nowrap rounded-xl bg-slate-100 px-3 py-3 text-xs text-slate-500">{{ $index }}. {{ $label }}</span>
            @endif
        @endforeach
    </nav>
    @if(session('status'))<div role="status" class="rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800">{{ session('status') }}</div>@endif
    @if($errors->any())<div role="alert" class="rounded-xl bg-red-50 p-4 text-sm text-red-800">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
    @if($step < 6)
    <form method="POST" enctype="multipart/form-data" action="{{ route('admin.setup.update', $draft) }}" class="panel space-y-5 p-5 sm:p-7">@csrf @method('PUT')<input type="hidden" name="step" value="{{ $step }}"><h2 class="text-lg font-black">{{ $step }}. {{ $labels[$step] }}</h2>
        @if($step === 2)
            <p class="text-sm leading-7 text-slate-500">یک دروازه زیرساخت یا اتصال تأییدشده همین مالک را انتخاب کنید. تغییر اتصال، انتخاب‌های بعدی پیش‌نویس را پاک می‌کند.</p><label class="block text-sm font-bold">اتصال ارائه‌دهنده<select name="gateway_id" required class="mt-2 w-full rounded-xl border border-slate-200 bg-white p-3"><option value="">انتخاب اتصال</option>@foreach($gateways as $item)<option value="{{ $item->id }}" @selected(old('gateway_id', $data['gateway_id'] ?? null) == $item->id)>{{ $item->display_name ?: $item->name }} · {{ $item->host }} · {{ $item->tenant_id ? 'اتصال مشتری' : 'زیرساخت' }}</option>@endforeach</select></label><a href="{{ route('sip-gateways.create', ['setup_id' => $draft->id]) }}" class="inline-block text-sm font-bold text-blue-700">+ ساخت اتصال جدید؛ سپس بازگشت به پیش‌نویس</a>
        @elseif($step === 3)
            <p class="text-sm text-slate-500">اتصال انتخاب‌شده: {{ $gateway?->name ?? 'دیگر در دسترس نیست' }}</p><div class="grid gap-5 sm:grid-cols-2"><fieldset><legend class="mb-3 text-sm font-bold">شماره جدید</legend><label class="text-sm"><input type="radio" name="number_mode" value="new" @checked(old('number_mode', $data['number_mode'] ?? 'new') === 'new')> افزودن شماره</label><input name="number" value="{{ old('number', $data['number'] ?? '') }}" placeholder="شماره DID" aria-label="شماره جدید" dir="ltr" class="mt-3 w-full rounded-xl border border-slate-200 p-3"></fieldset><fieldset><legend class="mb-3 text-sm font-bold">شماره موجود همین مالک</legend><label class="text-sm"><input type="radio" name="number_mode" value="existing" @checked(old('number_mode', $data['number_mode'] ?? '') === 'existing')> ادامه یا ویرایش شماره</label><select name="number_id" aria-label="شماره موجود" class="mt-3 w-full rounded-xl border border-slate-200 bg-white p-3"><option value="">انتخاب شماره</option>@foreach($numbers as $item)<option value="{{ $item->id }}" @selected(old('number_id', $data['number_id'] ?? null) == $item->id)>{{ $item->normalized_number }} · {{ $item->statusLabel() }}</option>@endforeach</select></fieldset></div><label class="block text-sm font-bold">برچسب<input name="label" value="{{ old('label', $data['label'] ?? '') }}" class="mt-2 w-full rounded-xl border border-slate-200 p-3"></label>
        @elseif($step === 4)
            <fieldset class="grid gap-5 sm:grid-cols-2"><div><label class="text-sm font-bold"><input type="radio" name="answerer" value="new" @checked(old('answerer', $data['answerer'] ?? 'new') === 'new')> ساخت تلفن برای یک نفر</label><input name="display_name" value="{{ old('display_name', $data['display_name'] ?? '') }}" placeholder="نام پاسخ‌گو" aria-label="نام پاسخ‌گوی جدید" class="mt-3 w-full rounded-xl border border-slate-200 p-3"><p class="mt-2 text-xs text-slate-500">شناسه و رمز تلفن پس از پایان راه‌اندازی نمایش داده می‌شود.</p></div><div><label class="text-sm font-bold"><input type="radio" name="answerer" value="existing" @checked(old('answerer', $data['answerer'] ?? '') === 'existing')> انتخاب داخلی، تیم یا منوی موجود</label><select name="destination_choice" aria-label="پاسخ‌گوی موجود" class="mt-3 w-full rounded-xl border border-slate-200 bg-white p-3">@include('shared.destination-options', ['selected' => old('destination_choice', $data['destination_choice'] ?? '')])</select></div></fieldset>
            @include('shared.schedule-editor', ['values' => $data, 'scheduleRoute' => $number?->inboundRoute, 'hasDraftAnnouncement' => (bool) $draft->announcement_upload, 'announcementUrl' => $number ? route('admin.sip-numbers.announcement', $number) : null])
        @else
            <p class="text-sm leading-7 text-slate-500">خروجی را مستقل از پاسخ‌گویی ورودی انتخاب کنید. شماره‌نمایش، همین DID و اتصال، {{ $gateway?->name }} خواهد بود.</p><div class="flex flex-wrap gap-4 text-sm"><label><input type="radio" name="outbound_enabled" value="0" @checked(! old('outbound_enabled', $data['outbound_enabled'] ?? false))> از تنظیم خروجی صرف‌نظر کن؛ مسیرهای قبلی حفظ شوند</label><label><input type="radio" name="outbound_enabled" value="1" @checked(old('outbound_enabled', $data['outbound_enabled'] ?? false))> خروجی برای داخلی‌های انتخاب‌شده</label></div>
            <div class="space-y-3 rounded-xl bg-slate-50 p-4">@if(($data['answerer'] ?? '') === 'new')<label class="block text-sm"><input type="checkbox" name="include_new_extension" value="1" @checked(old('include_new_extension', $data['include_new_extension'] ?? false))> تلفن جدید {{ $data['display_name'] }} مجاز به تماس خروجی باشد</label>@endif @foreach($extensions as $extension)<label class="block text-sm"><input type="checkbox" name="outbound_extension_ids[]" value="{{ $extension->id }}" @checked(in_array($extension->id, old('outbound_extension_ids', $data['outbound_extension_ids'] ?? [])))> {{ $extension->display_name ?: 'داخلی '.$extension->extension }} · <span dir="ltr">{{ $extension->extension }}</span></label>@endforeach</div><p class="text-xs leading-6 text-amber-800">اگر داخلی از قبل شماره تماس خروجی دیگری داشته باشد، انتخاب آن مسیر قبلی را جایگزین می‌کند. جزئیات در مرحله بررسی نمایش داده می‌شود.</p>
        @endif
        <div class="flex flex-wrap justify-between gap-3 border-t border-slate-100 pt-5"><a href="{{ $step === 2 ? route('admin.setup.index') : route('admin.setup.show', ['setup' => $draft->id, 'step' => $step - 1]) }}" class="p-3 text-sm font-bold text-slate-600">بازگشت</a><button class="rounded-xl bg-blue-600 px-6 py-3 text-sm font-bold text-white">ذخیره پیش‌نویس و ادامه ←</button></div>
    </form>
    @else
        <section class="panel space-y-5 p-6"><h2 class="text-lg font-black">۶. بررسی قبل از اعمال</h2><dl class="grid gap-4 text-sm sm:grid-cols-2"><div><dt class="text-slate-500">مالک</dt><dd class="mt-1 font-bold">{{ $tenant->name }}</dd></div><div><dt class="text-slate-500">اتصال</dt><dd class="mt-1 font-bold">{{ $gateway?->name ?? 'دیگر در دسترس نیست' }}</dd></div><div><dt class="text-slate-500">شماره</dt><dd class="mt-1 font-bold" dir="ltr">{{ $number?->normalized_number ?? $data['number'] ?? '' }}</dd></div><div><dt class="text-slate-500">پاسخ‌گوی ساعات باز</dt><dd class="mt-1 font-bold">{{ $data['answerer'] === 'new' ? 'تلفن جدید: '.$data['display_name'] : ($destinationLabels[$data['destination_choice']] ?? 'دیگر در دسترس نیست') }}</dd></div></dl>
        @if(!empty($data['label']))<p class="text-sm">برچسب شماره: <strong>{{ $data['label'] }}</strong></p>@endif
        @if($number)<div class="rounded-xl bg-amber-50 p-4 text-sm leading-7"><strong>تنظیمات فعلی شماره:</strong> اتصال {{ $number->providerGateway?->name ?? 'تعیین نشده' }}؛ پاسخ‌گو {{ $number->inboundRoute?->destinationLabel() ?? 'تعیین نشده' }}. با پایان راه‌اندازی، تنظیمات بالا جایگزین می‌شود.</div>@endif
        <div class="rounded-xl bg-slate-50 p-4 text-sm"><strong>زمان‌بندی</strong>@include('shared.schedule-summary', ['schedule' => ($data['schedule_mode'] ?? '') === 'scheduled' ? ['weekly' => $data['weekly'], 'timezone' => $data['timezone'], 'closed_dates' => $data['closed_dates'] ?? []] : null])@if(($data['schedule_mode'] ?? '') === 'scheduled')<p class="mt-3">ساعات بسته: {{ ['announcement' => 'پخش پیام، سپس پایان تماس', 'disconnect' => 'پایان تماس بدون پیام'][$data['closed_action']] ?? ($destinationLabels[$data['closed_action']] ?? 'دیگر در دسترس نیست') }}</p>@endif</div>
        <div class="text-sm"><h3 class="font-bold">تماس خروجی</h3>@if($data['outbound_enabled'])<p class="mt-2">داخلی‌های زیر از همین DID و اتصال {{ $gateway?->name }} استفاده می‌کنند:</p><ul class="mt-3 list-inside list-disc space-y-2">@if($data['include_new_extension'])<li>تلفن جدید: {{ $data['display_name'] }}</li>@endif @foreach($data['outbound_extension_ids'] as $id)@php($previous = collect($outboundAssignments)->firstWhere('sip_extension_id', $id))<li>{{ $extensions->firstWhere('id', $id)?->display_name ?: 'داخلی '.$extensions->firstWhere('id', $id)?->extension }}@if($previous)<span class="text-amber-800"> · مسیر قبلی از {{ \App\Models\SipNumber::find($previous['sip_number_id'])?->normalized_number }} جایگزین می‌شود</span>@endif</li>@endforeach</ul>@else<p class="mt-2 text-slate-500">مسیر خروجی جدید ساخته نمی‌شود؛ مسیرهای موجود حفظ می‌شوند.</p>@endif</div>
        @if($number?->status === 'pending')<p class="rounded-xl bg-amber-50 p-4 text-sm text-amber-800">این شماره در انتظار تأیید است؛ پایان راه‌اندازی آن را تأیید نمی‌کند.</p>@endif
        <form method="POST" action="{{ route('admin.setup.finish', $draft) }}" class="space-y-4 border-t border-slate-100 pt-5">@csrf<label class="flex items-start gap-2 text-sm leading-7"><input type="checkbox" name="confirm" value="1" required class="mt-2"> مالک، مقصدها، ساعت کاری و تغییرات خروجی را بررسی کردم و می‌خواهم این تنظیمات اعمال شود.</label><div class="flex justify-between"><a href="{{ route('admin.setup.show', ['setup' => $draft->id, 'step' => 5]) }}" class="p-3 text-sm font-bold text-slate-600">بازگشت</a><button class="rounded-xl bg-blue-600 px-6 py-3 text-sm font-bold text-white">اعمال تنظیمات و پایان راه‌اندازی</button></div></form></section>
    @endif
</div>
@endsection
