@extends('layouts.portal')
@section('title', $route ? 'ویرایش مسیر خروجی' : 'مسیر خروجی جدید')
@section('content')
<div class="mx-auto max-w-3xl space-y-5"><a href="{{ route('outbound-routes.index', $selectedNumberId ? ['sip_number_id' => $selectedNumberId] : []) }}" class="text-sm font-bold text-blue-700">← بازگشت به مسیرها</a><div><h1 class="text-2xl font-black">{{ $route ? 'ویرایش مسیر خروجی' : 'مسیر خروجی جدید' }}</h1><p class="mt-2 text-sm text-slate-600">شماره‌نمایش از DID انتخاب‌شده می‌آید و دروازه باید برای همان شماره و مالک مجاز باشد.</p></div>
    @if($errors->any())<div role="alert" class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><ul class="list-disc space-y-1 pr-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <form method="POST" action="{{ $route ? route('outbound-routes.update', $route) : route('outbound-routes.store') }}" class="space-y-5">@csrf @if($route) @method('PUT') @else <input type="hidden" name="tenant_id" value="{{ $tenant->id }}"> @endif
        <section class="panel space-y-5 p-5 sm:p-7"><div><h2 class="font-bold">هویت و مسیر تماس</h2><p class="mt-1 text-xs text-slate-500">مالک: {{ $tenant->name }}</p></div>
            @if($route)<div class="rounded-xl bg-slate-50 p-4 text-sm"><span class="font-bold">داخلی:</span> <span dir="ltr">{{ $route->sipExtension?->extension }}</span><span class="mt-1 block text-xs text-slate-500">برای تغییر داخلی، مسیر جدیدی بسازید.</span></div>@else
                <label class="block text-sm font-bold">داخلی<select name="sip_extension_id" required class="mt-2 w-full rounded-xl border border-slate-200 bg-white p-3 font-normal"><option value="">— انتخاب داخلی —</option>@foreach($extensions as $extension)<option value="{{ $extension->id }}" @selected((string) old('sip_extension_id') === (string) $extension->id)>{{ $extension->display_name ?: 'داخلی '.$extension->extension }} · {{ $extension->extension }}</option>@endforeach</select></label>
            @endif
            <label class="block text-sm font-bold">شماره‌نمایش (DID)<select name="sip_number_id" required class="mt-2 w-full rounded-xl border border-slate-200 bg-white p-3 font-normal"><option value="">— انتخاب شماره —</option>@foreach($numbers as $number)<option value="{{ $number->id }}" @selected((string) old('sip_number_id', $selectedNumberId) === (string) $number->id)>{{ $number->normalized_number }}</option>@endforeach</select></label>
            <label class="block text-sm font-bold">دروازه خروجی<select name="gateway_id" required class="mt-2 w-full rounded-xl border border-slate-200 bg-white p-3 font-normal"><option value="">— انتخاب دروازه مجاز —</option>@foreach($gateways as $gateway)<option value="{{ $gateway->id }}" @selected((string) old('gateway_id', $route?->gateway_id) === (string) $gateway->id)>{{ $gateway->name }}</option>@endforeach</select><span class="mt-1 block text-xs font-normal text-slate-500">فقط دروازه‌های فعال و تأییدشده برای خروجی نمایش داده می‌شوند.</span></label>
        </section>
        <section class="panel p-5 sm:p-7"><h2 class="font-bold">مجوز استفاده</h2><label class="mt-4 block rounded-xl border border-slate-200 p-4 text-sm"><input type="hidden" name="enabled" value="0"><input type="checkbox" name="enabled" value="1" @checked(old('enabled', $route?->enabled ?? true))> <strong>این داخلی بتواند از مسیر خروجی استفاده کند</strong><span class="mt-1 block text-xs text-slate-500">غیرفعال‌سازی این مسیر، تماس خروجی این داخلی را از این مسیر متوقف می‌کند.</span></label></section>
        @if($numbers->isEmpty() || $gateways->isEmpty() || (! $route && $extensions->isEmpty()))<p class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">برای ثبت مسیر، داخلی فعال، شماره مجاز برای خروجی و دروازه تأییدشده لازم است.</p>@endif
        <div class="sticky bottom-0 flex items-center justify-between gap-4 rounded-xl border border-slate-200 bg-white/95 p-4 shadow-lg backdrop-blur"><a href="{{ route('outbound-routes.index') }}" class="text-sm font-bold text-slate-600">انصراف</a><button @disabled($numbers->isEmpty() || $gateways->isEmpty() || (! $route && $extensions->isEmpty())) class="rounded-xl bg-blue-600 px-6 py-3 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-50">{{ $route ? 'ذخیره تغییرات' : 'ثبت مسیر' }}</button></div>
    </form>
    @if($route)<form method="POST" action="{{ route('outbound-routes.destroy', $route) }}" onsubmit="return confirm('حذف این مسیر، تماس خروجی داخلی را متوقف می‌کند. ادامه می‌دهید؟')">@csrf @method('DELETE')<button class="text-xs font-bold text-red-700">حذف مسیر خروجی</button></form>@endif
</div>
@endsection
