@extends('layouts.portal')
@section('title', 'شرایط زمانی')
@section('content')
<div class="mb-6 flex flex-wrap justify-between gap-3"><div><h1 class="text-2xl font-black">شرایط زمانی</h1><p class="mt-2 text-sm text-slate-500">ساعت کاری و اقدام ساعات بسته هر شماره را مدیریت کنید.</p></div><a href="{{ route('admin.sip-numbers.index', ['filter' => 'missing_route']) }}" class="rounded-xl border border-blue-200 p-3 text-sm font-bold text-blue-700">انتخاب شماره برای زمان‌بندی</a></div>
<form method="GET" class="panel mb-5 flex flex-wrap gap-3 p-4"><input name="q" value="{{ request('q') }}" placeholder="جست‌وجوی شماره" aria-label="جست‌وجوی شماره" class="rounded-lg border border-slate-200 p-2"><select name="tenant_id" aria-label="مالک" class="rounded-lg border border-slate-200 p-2"><option value="">همه مالک‌ها</option>@foreach($tenants as $tenant)<option value="{{ $tenant->id }}" @selected(request('tenant_id') == $tenant->id)>{{ $tenant->name }}</option>@endforeach</select><button class="rounded-lg bg-slate-900 px-4 py-2 text-sm text-white">فیلتر</button></form>
<div class="panel overflow-x-auto"><table class="w-full min-w-[700px] text-right text-sm"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4">شماره / مالک</th><th class="p-4">ساعت کاری</th><th class="p-4">ساعات باز</th><th class="p-4">ساعات بسته</th><th class="p-4">عملیات</th></tr></thead><tbody>
@forelse($routes as $route)<tr class="border-t border-slate-100"><td class="p-4"><span dir="ltr">{{ $route->sipNumber?->normalized_number }}</span><small class="mt-1 block text-slate-500">{{ $route->tenant?->name }} · {{ $route->enabled ? 'فعال' : 'غیرفعال' }}</small></td><td class="p-4">@include('shared.schedule-summary', ['schedule' => $route->schedule])</td><td class="p-4">{{ $route->destinationLabel() }}</td><td class="p-4">{{ $route->closedDestinationLabel() }}</td><td class="p-4"><a href="{{ route('admin.sip-numbers.inbound', $route->sip_number_id) }}" class="font-bold text-blue-700">ویرایش</a><a href="{{ route('admin.sip-numbers.setup', ['sip_number' => $route->sip_number_id, 'tab' => 'inbound']) }}" class="mt-2 block text-blue-700">پیش‌نمایش مسیر</a></td></tr>@empty<tr><td colspan="5" class="p-6 text-slate-500">هنوز شماره‌ای زمان‌بندی نشده است. در صفحه شماره، «تماس ورودی و ساعت کاری» را تنظیم کنید.</td></tr>@endforelse
</tbody></table><div class="p-4">{{ $routes->links() }}</div></div>
@endsection
