@extends('layouts.portal')
@section('title', $plan->name)
@section('content')
<a href="{{ route('admin.plans.index') }}" class="text-sm font-bold text-blue-700">بازگشت به پلن‌ها</a>
<div class="mt-5 flex flex-wrap items-start justify-between gap-4"><div><h1 class="text-2xl font-black">{{ $plan->name }}</h1><p class="mt-2 text-sm text-slate-500">{{ $plan->archived ? 'پلن آرشیوی · فقط مشاهده' : 'مدیریت ظرفیت‌ها و نسخه‌های پلن' }}</p></div>@unless($plan->archived)<a href="#{{ $drafts->isNotEmpty() ? 'draft-'.$drafts->first()->id : 'new-version' }}" class="rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white">{{ $drafts->isNotEmpty() ? 'ویرایش پیش‌نویس' : 'ساخت نسخه جدید' }}</a>@endunless</div>
<section class="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><div class="flex flex-wrap items-center justify-between gap-3"><h2 class="font-bold">آخرین نسخه منتشرشده</h2><span class="rounded-full bg-slate-100 px-3 py-1 text-xs">{{ $published ? 'نسخه '.$published->version.' · ثابت' : 'هنوز منتشر نشده' }}</span></div>
@if($published)<dl class="mt-6 grid grid-cols-3 gap-4">@foreach(['extensions' => 'داخلی', 'queues' => 'تیم پاسخ‌گویی', 'ivr_menus' => 'منوی تماس'] as $key => $label)<div><dt class="text-xs text-slate-500">{{ $label }}</dt><dd class="mt-2 text-3xl font-black">{{ $published->limits[$key] ?? '—' }}</dd></div>@endforeach</dl><p class="mt-5 text-sm leading-7 text-slate-500">سقف‌ها برای کل کسب‌وکار هستند. برای تغییر سقف‌ها، نسخه جدید بسازید.</p>@else<p class="mt-4 text-sm leading-7 text-slate-500">پیش‌نویس را تکمیل و مرور کنید تا اولین نسخه منتشر شود.</p>@endif
</section>
@foreach($drafts as $draft)
<section id="draft-{{ $draft->id }}" class="mt-6 scroll-mt-6 rounded-2xl border border-amber-200 bg-white p-6"><div class="flex flex-wrap items-center justify-between gap-3"><h2 class="font-bold">پیش‌نویس نسخه {{ $draft->version }}</h2><span class="rounded-full bg-amber-50 px-3 py-1 text-xs text-amber-800">{{ $plan->archived ? 'آرشیوی' : 'قابل ویرایش' }}</span></div>
@unless($plan->archived)<form method="POST" action="{{ route('admin.plans.edit-draft', $draft) }}" class="mt-6">@csrf @method('PUT')<div class="grid gap-5 sm:grid-cols-3">@include('admin.commerce.plans.limits', ['prefix' => 'draft-'.$draft->id, 'limits' => $draft->limits])</div><div class="mt-6 flex flex-wrap items-center gap-4"><button class="rounded-xl border border-slate-300 px-5 py-3 text-sm font-bold">ذخیره تغییرات</button><button name="intent" value="review" class="rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white">ذخیره و مرور انتشار ←</button></div></form>@else<p class="mt-4 text-sm text-slate-600">داخلی: {{ $draft->limits['extensions'] ?? '—' }} · تیم: {{ $draft->limits['queues'] ?? '—' }} · منو: {{ $draft->limits['ivr_menus'] ?? '—' }}</p>@endunless
</section>
@endforeach
@unless($plan->archived)
<details id="new-version" class="mt-6 rounded-2xl border border-slate-200 bg-white p-6" @if($drafts->isEmpty() || old('_editor') === 'new-version') open @endif><summary class="cursor-pointer font-bold">ساخت نسخه جدید</summary><p class="mt-3 text-sm leading-7 text-slate-500">{{ $published ? 'سقف‌ها از آخرین نسخه منتشرشده کپی شده‌اند.' : 'ظرفیت‌های اولین نسخه را مشخص کنید.' }} تغییرات به صورت پیش‌نویس ذخیره می‌شوند.</p><form method="POST" action="{{ route('admin.plans.version', $plan) }}" class="mt-5">@csrf<div class="grid gap-5 sm:grid-cols-3">@include('admin.commerce.plans.limits', ['prefix' => 'new-version', 'limits' => $published?->limits ?? []])</div><button class="mt-6 rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white">ساخت پیش‌نویس</button></form></details>
@endunless
<details class="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><summary class="cursor-pointer font-bold">تاریخچه نسخه‌ها · {{ $plan->versions->count() }}</summary><div class="mt-5 divide-y divide-slate-100">@foreach($plan->versions as $version)<div class="flex flex-wrap justify-between gap-3 py-4 text-sm"><div class="font-bold">نسخه {{ $version->version }} <span class="mr-2 text-xs font-normal text-slate-500">{{ $version->published_at ? 'منتشرشده · '.$version->published_at->format('Y/m/d') : 'پیش‌نویس' }}</span></div><p class="text-slate-600">داخلی: {{ $version->limits['extensions'] ?? '—' }} · تیم: {{ $version->limits['queues'] ?? '—' }} · منو: {{ $version->limits['ivr_menus'] ?? '—' }}</p></div>@endforeach</div></details>
<section id="offers" class="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><h2 class="font-bold">پیشنهادهای فروش فعال · {{ $offers->count() }}</h2><p class="mt-2 text-sm leading-7 text-slate-500">مبلغ ماهانه هنگام انتشار پیشنهاد فروش شماره تعیین می‌شود. هر پیشنهاد به نسخه مشخصی از پلن متصل است.</p><div class="mt-4 divide-y divide-slate-100">@forelse($offers as $offer)<a href="{{ route('admin.inventory.show', $offer->sip_number_id) }}" class="flex flex-wrap justify-between gap-3 py-4 text-sm text-blue-700"><span dir="ltr">{{ $offer->number?->number ?? $offer->sip_number_id }}</span><span>نسخه {{ $offer->planVersion->version }} · {{ number_format($offer->monthly_amount) }} تومان / ماه ←</span></a>@empty<p class="py-3 text-sm text-slate-500">پیشنهاد فروش فعالی وجود ندارد.</p>@endforelse</div></section>
@unless($plan->archived)<details class="mt-6 rounded-2xl border border-slate-200 p-5" @if(old('_editor') === 'archive') open @endif><summary class="cursor-pointer text-sm font-bold text-slate-600">سایر اقدامات</summary><h2 class="mt-5 font-bold">آرشیو پلن</h2>@if($offers->isNotEmpty())<p class="mt-3 text-sm leading-7 text-amber-800">برای آرشیو، ابتدا {{ $offers->count() }} پیشنهاد فروش فعال بالا را بردارید.</p><a href="#offers" class="mt-3 inline-block text-sm font-bold text-blue-700">مشاهده پیشنهادهای مسدودکننده ↑</a>@else<p class="mt-3 text-sm leading-7 text-slate-500">پلن آرشیوی امکان ساخت، ویرایش یا انتشار نسخه ندارد. تاریخچه نسخه‌ها حفظ می‌شود.</p><form method="POST" action="{{ route('admin.plans.archive', $plan) }}" class="mt-4 max-w-xl">@csrf<input type="hidden" name="_editor" value="archive"><label for="archive-reason" class="block text-sm font-bold">دلیل آرشیو</label><textarea id="archive-reason" name="reason" required maxlength="1000" rows="3" class="mt-2 w-full rounded-xl border border-slate-300 p-3">{{ old('reason') }}</textarea>@error('reason')<p class="mt-2 text-sm text-red-700">{{ $message }}</p>@enderror<button class="mt-3 rounded-xl border border-red-200 bg-white px-5 py-3 text-sm font-bold text-red-700">تأیید آرشیو پلن</button></form>@endif</details>@endunless
@endsection
