@extends('layouts.portal')
@section('title', 'پلن‌های ماهانه')
@section('content')
<div class="flex flex-wrap items-start justify-between gap-4"><div><h1 class="text-2xl font-black">پلن‌های ماهانه</h1><p class="mt-2 text-sm leading-7 text-slate-500">ظرفیت‌ها، پیش‌نویس‌ها و نسخه‌های منتشرشده را مدیریت کنید.</p></div><a href="{{ route('admin.plans.create') }}" class="rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white">+ ایجاد پلن</a></div>
<div class="mt-7 rounded-2xl border border-slate-200 bg-white">
<form method="GET" class="flex flex-wrap items-end gap-3 border-b border-slate-100 p-5"><div class="min-w-48 flex-1"><label for="plan-search" class="block text-xs font-bold text-slate-600">جست‌وجوی نام پلن</label><input id="plan-search" name="q" value="{{ $search }}" placeholder="نام پلن…" class="mt-2 w-full rounded-xl border border-slate-300 p-3 text-sm"></div><div><label for="plan-filter" class="block text-xs font-bold text-slate-600">نمایش</label><select id="plan-filter" name="filter" class="mt-2 rounded-xl border border-slate-300 p-3 text-sm">@foreach(['all' => 'همه پلن‌های فعال', 'published' => 'دارای نسخه منتشرشده', 'unpublished' => 'بدون نسخه منتشرشده', 'archived' => 'آرشیوی'] as $value => $label)<option value="{{ $value }}" @selected($filter === $value)>{{ $label }}</option>@endforeach</select></div><button class="rounded-xl bg-slate-100 px-5 py-3 text-sm font-bold">اعمال</button>@if($search || $filter !== 'all')<a href="{{ route('admin.plans.index') }}" class="px-2 py-3 text-sm text-blue-700">پاک کردن فیلتر</a>@endif</form>
<div class="hidden grid-cols-12 gap-4 border-b border-slate-100 px-6 py-3 text-xs font-bold text-slate-500 md:grid"><span class="col-span-3">نام پلن</span><span class="col-span-2">نسخه منتشرشده</span><span class="col-span-3">داخلی / تیم / منو</span><span class="col-span-2">پیش‌نویس</span><span class="col-span-2">مدیریت</span></div>
@forelse($plans as $plan)
@php($published = $plan->versions->first(fn($v) => $v->published_at !== null))
@php($draftCount = $plan->versions->whereNull('published_at')->count())
<div class="grid gap-4 border-b border-slate-100 p-5 last:border-0 md:grid-cols-12 md:items-center md:px-6"><div class="md:col-span-3"><a href="{{ route('admin.plans.show', $plan) }}" class="font-bold text-slate-900 hover:text-blue-700">{{ $plan->name }}</a>@if($plan->archived)<span class="mr-2 rounded-full bg-slate-100 px-2 py-1 text-xs">آرشیوی</span>@endif</div><div class="text-sm md:col-span-2">@if($published)<span class="rounded-full bg-emerald-50 px-3 py-1 text-emerald-800">نسخه {{ $published->version }}</span>@else<span class="text-slate-500">منتشر نشده</span>@endif</div><div class="text-sm text-slate-600 md:col-span-3">@if($published)<span class="md:hidden">داخلی / تیم / منو: </span>{{ $published->limits['extensions'] ?? '—' }} / {{ $published->limits['queues'] ?? '—' }} / {{ $published->limits['ivr_menus'] ?? '—' }}@else—@endif</div><div class="text-sm md:col-span-2">@if($draftCount)<span class="rounded-full bg-amber-50 px-3 py-1 text-amber-800">{{ $draftCount }} پیش‌نویس</span>@else<span class="text-slate-400">بدون پیش‌نویس</span>@endif</div><a href="{{ route('admin.plans.show', $plan) }}" class="text-sm font-bold text-blue-700 md:col-span-2">مدیریت پلن ←</a></div>
@empty<div class="px-6 py-16 text-center"><p class="font-bold">{{ $search || $filter !== 'all' ? 'پلنی با این فیلتر پیدا نشد.' : 'هنوز پلنی ایجاد نشده است.' }}</p><p class="mt-2 text-sm text-slate-500">{{ $search || $filter !== 'all' ? 'جست‌وجو یا فیلتر را تغییر دهید.' : 'با ایجاد اولین پیش‌نویس شروع کنید.' }}</p></div>@endforelse
</div><div class="mt-5">{{ $plans->links() }}</div>
<p class="mt-5 text-xs leading-6 text-slate-500">سقف‌ها برای کل کسب‌وکار هستند. مبلغ ماهانه در پیشنهاد فروش شماره تعیین می‌شود.</p>
@endsection
