@extends('layouts.portal')
@section('title', 'آماده‌سازی موجودی فروش')
@section('content')
<a href="{{ route('admin.sip-numbers.index', ['scope' => 'stock']) }}" class="text-sm text-blue-700">← موجودی فروش</a>
<h1 class="my-4 text-2xl font-black" dir="ltr">{{ $number->normalized_number }}</h1>
<p class="mb-5 text-sm text-slate-500">انتشار پیشنهاد، مالک ایجاد نمی‌کند و تماس یا درگاه پرداخت را فعال نمی‌کند. قیمت‌ها به تومان (IRT) هستند.</p>
<div class="panel mb-5 p-5"><h2 class="font-bold">بررسی آمادگی</h2>@if(count($issues))<ul class="mt-3 list-disc space-y-2 pr-5 text-sm text-amber-800">@foreach($issues as $issue)<li>{{ $issue }}</li>@endforeach</ul>@else<p class="mt-3 text-emerald-700">تنظیمات فعلی و بررسی فنی برای انتشار معتبر است؛ وضعیت زنده ثبت نزد ارائه‌دهنده جداگانه بررسی می‌شود.</p>@endif
@if($number->reviewed_at)<p class="mt-3 text-sm">آخرین بررسی: {{ $number->reviewed_at }} — {{ $number->readiness_evidence }}</p>@endif</div>
@if($number->currentOffer)
<div class="panel mb-5 p-5"><h2 class="font-bold">پیشنهاد منتشرشده</h2><p class="my-3">{{ $number->currentOffer->planVersion->plan->name }} · نسخه {{ $number->currentOffer->planVersion->version }} · {{ number_format($number->currentOffer->monthly_amount) }} تومان / ماه</p>
<form method="POST" action="{{ route('admin.inventory.withdraw', $number) }}" class="flex flex-wrap gap-3">@csrf<input type="hidden" name="revision" value="{{ $number->inventory_revision }}"><label>دلیل برداشت انتشار<input name="reason" required maxlength="1000" class="mx-2 rounded-lg border p-2"></label><button class="rounded-lg bg-amber-100 p-3 font-bold">برداشتن انتشار</button></form></div>
@else
<form method="POST" action="{{ route('admin.inventory.update', $number) }}" class="panel mb-5 grid gap-4 p-5 sm:grid-cols-2">@csrf @method('PUT')<input type="hidden" name="revision" value="{{ $number->inventory_revision }}">
<label>برچسب<input class="mt-1 w-full rounded-lg border p-3" name="label" value="{{ old('label', $number->label) }}"></label>
<label>اتصال زیرساخت<select name="provider_gateway_id" class="mt-1 w-full rounded-lg border p-3"><option value="">تعیین نشده</option>@foreach($gateways as $gateway)<option value="{{ $gateway->id }}" @selected(old('provider_gateway_id', $number->provider_gateway_id) == $gateway->id)>{{ $gateway->name }}</option>@endforeach</select></label>
<label class="sm:col-span-2">پیش‌شماره‌های مجاز مقصد<input name="destination_prefixes_text" class="mt-1 w-full rounded-lg border p-3" dir="ltr" value="{{ old('destination_prefixes_text', implode(' ', $number->destination_prefixes ?? [])) }}"></label>
<div class="flex flex-wrap gap-4">@foreach(['enabled' => 'فعال در تنظیمات', 'inbound_enabled' => 'ورودی', 'outbound_enabled' => 'خروجی'] as $field => $label)<label><input type="hidden" name="{{ $field }}" value="0"><input type="checkbox" name="{{ $field }}" value="1" @checked(old($field, $number->$field))> {{ $label }}</label>@endforeach</div><button class="rounded-xl bg-blue-600 p-3 font-bold text-white">ذخیره تنظیمات</button></form>
@if(in_array($number->inventory_state, ['draft', 'available']))
<form method="POST" action="{{ route('admin.inventory.review', $number) }}" class="panel mb-5 p-5">@csrf<input type="hidden" name="revision" value="{{ $number->inventory_revision }}"><label class="block font-bold">شواهد بررسی فنی<textarea name="evidence" required minlength="10" maxlength="2000" class="mt-2 w-full rounded-lg border p-3" placeholder="نتیجه بررسی اتصال و قابلیت شماره؛ هیچ رمز یا اطلاعات محرمانه‌ای وارد نکنید.">{{ old('evidence') }}</textarea></label><button class="mt-3 rounded-xl bg-slate-900 p-3 text-white">ثبت بررسی تنظیمات فعلی</button></form>
<form method="POST" action="{{ route('admin.inventory.publish', $number) }}" class="panel mb-5 grid gap-4 p-5 sm:grid-cols-2">@csrf<input type="hidden" name="revision" value="{{ $number->inventory_revision }}"><label>نسخه پلن ماهانه<select name="plan_version_id" required class="mt-1 w-full rounded-lg border p-3"><option value="">انتخاب پلن</option>@foreach($versions as $version)<option value="{{ $version->id }}">{{ $version->plan->name }} · نسخه {{ $version->version }}</option>@endforeach</select></label><label>کل مبلغ ماهانه (تومان / IRT)<input name="monthly_amount" required type="number" min="1" max="1000000000000" step="1" value="{{ old('monthly_amount') }}" class="mt-1 w-full rounded-lg border p-3"></label><p class="text-sm text-slate-500">این مبلغ کل اشتراک شماره است. هزینه پلن جداگانه‌ای افزوده نمی‌شود.</p><button class="rounded-xl bg-emerald-700 p-3 font-bold text-white">انتشار پیشنهاد</button></form>
@endif
<form method="POST" action="{{ route('admin.inventory.transition', $number) }}" class="panel mb-5 flex flex-wrap items-end gap-3 p-5">@csrf<input type="hidden" name="revision" value="{{ $number->inventory_revision }}"><input type="hidden" name="action" value="{{ $number->inventory_state === 'disabled' ? 'draft' : 'disable' }}"><label>دلیل تغییر وضعیت<input name="reason" required maxlength="1000" class="mt-1 block rounded-lg border p-3"></label><button class="rounded-xl border p-3">{{ $number->inventory_state === 'disabled' ? 'بازگشت به پیش‌نویس' : 'غیرفعال کردن موجودی' }}</button></form>
@endif
<div class="panel p-5"><h2 class="font-bold">تاریخچه پیشنهادها</h2>@forelse($number->offers->sortByDesc('id') as $offer)<p class="mt-3 text-sm">{{ $offer->planVersion->plan->name }} · نسخه {{ $offer->planVersion->version }} · {{ number_format($offer->monthly_amount) }} تومان / ماه · {{ $offer->withdrawn_at ? 'برداشته‌شده' : 'منتشرشده' }}</p>@empty<p class="mt-3 text-sm text-slate-500">هنوز پیشنهادی ثبت نشده است.</p>@endforelse</div>
@endsection
