@extends('layouts.portal')
@section('title', 'داخلی‌های SIP')
@section('content')
<div class="mb-6 flex flex-wrap items-start justify-between gap-4"><div><h1 class="text-xl font-extrabold">داخلی‌های SIP</h1><p class="mt-1 text-sm text-slate-500">داخلی‌ها و دسترسی آن‌ها را مدیریت کنید.</p></div><a href="{{ route('sip-extensions.create') }}" class="rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white">+ داخلی جدید</a></div>
@if(session('status'))<div role="status" class="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{{ session('status') }}</div>@endif
@php($credentials = session('extension_credentials'))
@if($credentials)<div role="status" class="mb-5 rounded-xl border border-blue-200 bg-blue-50 p-5 text-sm text-blue-950"><h2 class="font-bold">اطلاعات اتصال · فقط همین بار نمایش داده می‌شود</h2><p class="mt-1 text-xs">رمز را در محل امن نگه دارید و فقط به صاحب داخلی تحویل دهید.</p><dl class="mt-4 grid gap-3 sm:grid-cols-4">@foreach(['extension' => 'داخلی', 'password' => 'رمز', 'host' => 'سرور', 'port' => 'پورت'] as $key => $label)<div><dt class="text-xs text-slate-500">{{ $label }}</dt><dd class="mt-1 select-all break-all font-mono" dir="ltr">{{ $credentials[$key] ?? '—' }}</dd></div>@endforeach</dl></div>@endif
@if($errors->any())<div role="alert" class="mb-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{{ $errors->first() }}</div>@endif
<section class="panel overflow-hidden"><div class="border-b border-slate-100 p-5"><h2 class="font-bold">داخلی‌های ثبت‌شده</h2></div><div class="overflow-x-auto"><table class="w-full min-w-[560px] text-right text-sm"><thead class="bg-slate-50 text-[10px] font-bold uppercase tracking-wider text-slate-500"><tr><th class="px-5 py-3">داخلی</th><th class="px-5 py-3">نام نمایشی</th><th class="px-5 py-3">وضعیت پیکربندی</th><th class="px-5 py-3">اقدام</th></tr></thead><tbody class="divide-y divide-slate-100">
    @forelse($extensions as $extension)<tr class="hover:bg-slate-50"><td class="px-5 py-4 font-bold" dir="ltr">{{ $extension->extension }}</td><td class="px-5 py-4">{{ $extension->display_name ?: '—' }}</td><td class="px-5 py-4"><span class="rounded-full px-3 py-1 text-xs font-bold {{ $extension->enabled ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600' }}">{{ $extension->enabled ? 'فعال' : 'غیرفعال' }}</span></td><td class="px-5 py-4"><a href="{{ route('sip-extensions.edit', $extension) }}" class="text-xs font-bold text-blue-700">ویرایش و رمز عبور</a></td></tr>
    @empty<tr><td colspan="4" class="px-5 py-10 text-center text-slate-500">هنوز داخلی‌ای ثبت نشده است. <a href="{{ route('sip-extensions.create') }}" class="font-bold text-blue-700">داخلی جدید بسازید</a>.</td></tr>@endforelse
</tbody></table></div></section>
@endsection
