@extends('layouts.portal')
@section('title', 'تنظیم ضبط شماره')
@section('content')
<div class="mx-auto max-w-4xl space-y-6">
    <header><a href="{{ route('recordings.settings') }}" class="text-xs font-bold text-blue-700">← همه شماره‌ها</a><h1 class="mt-3 text-2xl font-black">ضبط تماس <span dir="ltr" class="inline-block">{{ $number->number }}</span></h1><p class="mt-2 text-sm leading-7 text-slate-500">تغییرات برای تماس‌های جدید اعمال می‌شود. خاموش کردن ضبط، فایل‌های قبلی را حذف نمی‌کند.</p></header>
    @if(!config('voip.recordings.enabled'))<p role="status" class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">ضبط هنوز در سرور فعال نشده است. می‌توانید تنظیمات را ذخیره کنید.</p>@endif
    <form method="POST" action="{{ route('recordings.numbers.update',$number) }}" enctype="multipart/form-data" class="panel overflow-hidden">@csrf @method('PUT')
        <div class="space-y-6 p-6"><h2 class="text-lg font-black">کدام تماس‌ها ضبط شوند؟</h2><div class="grid gap-3 sm:grid-cols-2">@foreach(['off'=>['خاموش','هیچ تماس جدیدی ضبط نمی‌شود.'],'inbound'=>['تماس‌های ورودی','تماس‌هایی که به این شماره می‌رسند.'],'outbound'=>['تماس‌های خروجی','تماس‌هایی که با شماره مجاز این خط برقرار می‌شوند.'],'both'=>['ورودی و خروجی','همه تماس‌های مجاز این شماره.']] as $value=>$option)<label class="flex cursor-pointer items-start gap-3 rounded-2xl border border-slate-200 p-4 has-[:checked]:border-blue-500 has-[:checked]:bg-blue-50"><input type="radio" name="directions" value="{{ $value }}" @checked(old('directions',$setting?->directions ?? 'off') === $value) class="mt-1 accent-blue-600"><span><strong class="block text-sm">{{ $option[0] }}</strong><span class="mt-1 block text-xs leading-6 text-slate-500">{{ $option[1] }}</span></span></label>@endforeach</div>
            <div class="grid gap-5 sm:grid-cols-2"><label class="text-sm font-bold">محتوای ضبط<select name="coverage" class="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-normal"><option value="conversation" @selected(old('coverage',$setting?->coverage ?? 'conversation') === 'conversation')>فقط مکالمه پس از اتصال پاسخ‌گو</option><option value="full" @selected(old('coverage',$setting?->coverage) === 'full')>از پاسخ خط، همراه منو و زمان انتظار</option></select></label><label class="text-sm font-bold">چند روز نگهداری شود؟<input type="number" name="retention_days" min="1" max="365" required value="{{ old('retention_days',$setting?->retention_days ?? 30) }}" class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal"><span class="mt-2 block text-xs font-normal text-slate-500">۱ تا ۳۶۵ روز از پایان تماس؛ پس از آن صدا خودکار حذف می‌شود.</span></label></div>
            <section class="space-y-3 rounded-2xl border border-slate-200 p-5"><label class="flex items-start gap-3 text-sm font-bold"><input type="hidden" name="announcement_enabled" value="0"><input type="checkbox" name="announcement_enabled" value="1" @checked(old('announcement_enabled',$setting?->announcement_enabled)) class="mt-1 accent-blue-600"><span>پخش پیام اطلاع‌رسانی ضبط برای تماس‌های ورودی</span></label><p class="text-xs leading-6 text-slate-500">پیام پیش از منو یا اتصال پاسخ‌گو برای تماس‌گیرنده پخش می‌شود. برای مثال: «این مکالمه ضبط می‌شود». این پیام برای مخاطب تماس خروجی پخش نمی‌شود.</p><label class="block text-xs font-bold">فایل پیام<input type="file" name="announcement" accept="audio/wav,audio/mpeg,audio/mp4,.m4a" class="mt-2 block w-full text-xs"><span class="mt-2 block font-normal text-slate-500">WAV، MP3 یا M4A؛ حداکثر ۸ مگابایت. فقط ۱۵ ثانیه اول استفاده می‌شود.</span></label>@if($setting?->announcement_path)<audio controls preload="none" src="{{ route('recordings.announcement',$number) }}" class="w-full"></audio>@endif</section>
            <details><summary class="cursor-pointer text-sm font-bold text-blue-700">تنظیم پیشرفته مدت ضبط</summary><label class="mt-4 block text-sm">حداکثر مدت ضبط هر تماس (دقیقه)<input type="number" name="max_minutes" min="1" max="120" required value="{{ old('max_minutes',$setting?->max_minutes ?? 60) }}" class="mt-2 block w-full rounded-xl border border-slate-200 px-4 py-3 sm:w-56"><span class="mt-2 block text-xs leading-6 text-slate-500">۱ تا ۱۲۰ دقیقه؛ پس از این مدت فقط ضبط متوقف می‌شود و تماس ادامه دارد. فضای لازم تا این سقف برای تماس‌های هم‌زمان رزرو می‌شود.</span></label></details>
        </div><div class="border-t border-slate-100 bg-slate-50 p-5"><button class="rounded-xl bg-blue-600 px-6 py-3 text-sm font-bold text-white hover:bg-blue-700">ذخیره تنظیمات شماره</button></div>
    </form>
    <form method="POST" action="{{ route('recordings.storage',$number->tenant_id) }}" class="panel space-y-5 p-6">@csrf @method('PUT')<div><h2 class="text-lg font-black">فضای ضبط مجموعه</h2><p class="mt-2 text-xs leading-6 text-slate-500">این تنظیم بین همه شماره‌های همین مجموعه مشترک است. استفاده فعلی: {{ number_format($usage['bytes']/1048576,1) }} مگابایت؛ رزروشده: {{ number_format($usage['reserved_bytes']/1048576,1) }} مگابایت.</p></div><label class="block text-sm font-bold">سقف فضای ضبط (مگابایت)<input type="number" name="quota_mb" min="128" max="{{ config('voip.recordings.max_quota_mb') }}" required value="{{ old('quota_mb',$storageSetting->quota_mb) }}" class="mt-2 block w-full rounded-xl border border-slate-200 px-4 py-3 font-normal sm:w-56"></label><fieldset class="space-y-3"><legend class="mb-3 text-sm font-bold">وقتی فضا پر شد</legend><label class="flex items-start gap-3 rounded-xl border border-slate-200 p-4"><input type="radio" name="overflow" value="stop" @checked(old('overflow',$storageSetting->overflow)==='stop') class="mt-1 accent-blue-600"><span class="text-sm"><strong>ضبط تماس‌های جدید متوقف شود</strong><span class="mt-1 block text-xs leading-6 text-slate-500">تماس‌ها ادامه دارند و فایل‌های قبلی حفظ می‌شوند.</span></span></label><label class="flex items-start gap-3 rounded-xl border border-slate-200 p-4"><input type="radio" name="overflow" value="oldest" @checked(old('overflow',$storageSetting->overflow)==='oldest') class="mt-1 accent-blue-600"><span class="text-sm"><strong>قدیمی‌ترین فایل‌های آماده حذف شوند</strong><span class="mt-1 block text-xs leading-6 text-slate-500">برای ضبط تماس جدید، صداهای قدیمی پیش از پایان مدت نگهداری هم ممکن است برای همیشه حذف شوند. فایل‌های در حال ضبط حذف نمی‌شوند.</span></span></label></fieldset><button class="rounded-xl border border-blue-200 px-5 py-3 text-sm font-bold text-blue-700">ذخیره تنظیمات فضا</button></form>
    @if($existingCount)<details class="panel p-6"><summary class="cursor-pointer font-bold text-amber-800">تغییر نگهداری {{ $existingCount }} فایل قبلی</summary><form method="POST" action="{{ route('recordings.retention',$number) }}" class="mt-4 space-y-4">@csrf<p class="text-sm leading-7 text-slate-600">این کار فقط فایل‌های موجود این شماره را تغییر می‌دهد. زمان حذف از پایان تماس محاسبه می‌شود؛ فایل‌های قدیمی‌تر از مدت جدید در اجرای بعدی پاک‌سازی حذف خواهند شد.</p><label class="block text-sm">مدت نگهداری جدید (روز)<input type="number" name="retention_days" min="1" max="365" required value="{{ $setting?->retention_days ?? 30 }}" class="mt-2 block w-40 rounded-xl border border-slate-200 px-3 py-3"></label><label class="flex items-start gap-3 text-sm"><input type="checkbox" name="confirm" value="1" required class="mt-1"><span>اعمال روی {{ $existingCount }} فایل و حذف خودکار فایل‌های منقضی را تأیید می‌کنم.</span></label><button class="rounded-xl border border-amber-300 bg-amber-50 px-5 py-3 text-sm font-bold text-amber-900">اعمال روی فایل‌های قبلی</button></form></details>@endif
</div>
@endsection
