@extends('layouts.portal')
@section('title', 'خط‌های من')
@section('content')
<header class="flex flex-wrap items-start justify-between gap-4"><div><h1 class="text-2xl font-black sm:text-3xl">خط‌های من</h1><p class="mt-2 text-sm leading-7 text-slate-600">پاسخ‌گوی تماس‌ها را انتخاب کنید، تلفن‌ها را وصل کنید و تنظیمات خط را یک‌جا ببینید.</p></div>@if(config('commerce.catalog_enabled') && auth()->user()->hasPermission('numbers.purchase'))<a class="commerce-button" href="{{ route('customer.numbers.index') }}">خرید شماره جدید</a>@endif</header>
@if(isset($pendingOrders) && $pendingOrders->isNotEmpty())<section class="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 class="font-bold text-amber-950">خرید شما هنوز تکمیل نشده است</h2><p class="mt-2 text-sm leading-7 text-amber-900">وضعیت پرداخت و تخصیص شماره را در سفارش‌ها دنبال کنید. اگر پرداخت در حال بررسی است، دوباره پرداخت نکنید.</p><a class="mt-3 inline-flex min-h-11 items-center text-sm font-bold text-blue-700" href="{{ route('customer.orders.index') }}">پیگیری سفارش‌ها ←</a></section>@endif
<div class="mt-7 grid gap-5 md:grid-cols-2">
@forelse($numbers as $number)
@php($hasAnswer = $number->inboundRoute && $number->inboundRoute->enabled)
<article class="panel p-6"><div class="flex flex-wrap items-center justify-between gap-3"><h2 class="text-2xl font-black"><bdi dir="ltr">{{ $number->number }}</bdi></h2><span class="rounded-full px-3 py-1 text-xs font-bold {{ $hasAnswer ? 'bg-blue-50 text-blue-700' : 'bg-amber-50 text-amber-800' }}">{{ $hasAnswer ? 'پاسخ‌گو تنظیم شده' : 'منتظر انتخاب پاسخ‌گو' }}</span></div><p class="mt-5 text-sm text-slate-600">پاسخ‌گوی ورودی: <strong class="text-slate-900">{{ $number->inboundRoute?->destinationLabel() ?? 'هنوز انتخاب نشده' }}</strong></p><p class="mt-3 text-xs leading-6 text-slate-500">{{ $hasAnswer ? 'برای اطمینان از اتصال، ثبت تلفن و تماس ورودی و خروجی را بررسی کنید.' : 'اولین قدم: مشخص کنید تماس‌ها به یک شخص، تیم یا منوی صوتی برسند.' }}</p><a href="{{ route('customer.lines.show', $number) }}" class="commerce-button mt-5 w-full">{{ $hasAnswer ? 'مدیریت و اتصال تلفن‌ها' : 'شروع تنظیم خط' }}</a></article>
@empty
<section class="panel p-7 text-center md:col-span-2 sm:p-12"><span class="mx-auto grid size-14 place-items-center rounded-2xl bg-blue-50 text-2xl text-blue-700" aria-hidden="true">☎</span><h2 class="mt-5 text-xl font-black">اولین خط کسب‌وکارتان را بخرید</h2><p class="mx-auto mt-3 max-w-lg text-sm leading-8 text-slate-600">شماره و پلن مناسب را انتخاب کنید. بعد از تأیید پرداخت، همین‌جا پاسخ‌گو و تلفن‌های خود را تنظیم می‌کنید.</p>@if(config('commerce.catalog_enabled') && auth()->user()->hasPermission('numbers.purchase'))<a class="commerce-button mt-6" href="{{ route('customer.numbers.index') }}">انتخاب شماره و پلن</a>@else<p class="mt-5 text-sm text-slate-600">برای دریافت خط با پشتیبانی تماس بگیرید.</p>@endif<a class="commerce-link mt-4 block text-sm font-bold" href="{{ route('customer.orders.index') }}">قبلاً خرید کرده‌اید؟ پیگیری سفارش</a></section>
@endforelse
</div>
@endsection
