@extends('layouts.portal')
@section('title', 'تنظیم خط')
@section('content')
@php
    $route = $number->inboundRoute;
    $hasAnswer = $route && $route->enabled;
    $answerer = old('answerer', $route?->destination_type === 'queue' ? 'team' : ($route?->destination_type === 'ivr' ? 'menu' : ($route?->destination_type === 'extension' || $extensions->where('enabled', true)->isNotEmpty() ? 'existing' : 'new')));
    $credentials = $credentials ?? null;
@endphp
<div data-line-workspace>
<a class="commerce-link mb-4 inline-flex min-h-11 items-center text-sm font-bold" href="{{ route('customer.lines.index') }}">→ خط‌های من</a>
<header class="flex flex-wrap items-start justify-between gap-4"><div><h1 class="text-2xl font-black sm:text-3xl">تنظیم خط <bdi dir="ltr">{{ $number->number }}</bdi></h1><p class="mt-2 text-sm leading-7 text-slate-600">سه قدم تا پاسخ‌گویی: انتخاب مقصد تماس، اتصال تلفن و یک تماس آزمایشی.</p></div><span class="rounded-full px-4 py-2 text-xs font-bold {{ $hasAnswer ? 'bg-blue-50 text-blue-800' : 'bg-amber-50 text-amber-900' }}">{{ $hasAnswer ? 'پاسخ‌گو تنظیم شده' : 'آماده برای تنظیم' }}</span></header>
<nav class="panel mt-6 p-4" aria-label="مراحل اتصال خط"><ol class="grid gap-3 text-sm sm:grid-cols-3">@foreach(['انتخاب پاسخ‌گو'=>'answer','اتصال تلفن'=>'phones','بررسی تماس'=>'check'] as $label=>$anchor)<li><a class="flex min-h-11 items-center gap-3 rounded-xl px-3 font-bold text-blue-900 hover:bg-blue-50" href="#{{ $anchor }}"><span class="grid size-7 shrink-0 place-items-center rounded-full bg-blue-100 text-xs">{{ $loop->iteration }}</span>{{ $label }}</a></li>@endforeach</ol></nav>
@if($subscription)<p class="mt-4 text-xs leading-7 text-slate-600">{{ $subscription->status === 'pending_activation' ? 'ماه اول با ذخیره اولین پاسخ‌گو شروع می‌شود.' : 'پایان دوره: '.($subscription->period_ends_at?->timezone('Asia/Tehran')->format('Y/m/d H:i') ?? '—') }} · ظرفیت حساب: {{ $limits['extensions'] }} تلفن، {{ $limits['queues'] }} تیم و {{ $limits['ivr_menus'] }} منو</p>@endif
@if(isset($serviceReady) && !$serviceReady)<div role="status" class="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-7 text-amber-900">{{ $serviceMessage ?? 'سرویس خط در حال بررسی است. تنظیمات ذخیره می‌شوند؛ برای شروع تماس وضعیت سرویس باید تأیید شود.' }}</div>@endif
@if($errors->any())<div role="alert" class="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-900"><p class="font-bold">برای ذخیره، این موارد را اصلاح کنید:</p><ul class="mt-2 list-inside list-disc space-y-2">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="mt-6 grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_320px]">
<div class="space-y-6">
<section id="answer" class="panel scroll-mt-5 p-5 sm:p-7"><h2 class="text-lg font-black">۱. چه کسی تماس‌ها را پاسخ دهد؟</h2><p class="mt-2 text-sm leading-7 text-slate-600">برای شروع، یک تلفن بسازید. برای چند همکار، تیم پاسخ‌گویی یا منوی صوتی انتخاب کنید.</p>
<fieldset @disabled(!$canManage)><form class="mt-5 space-y-5" method="POST" action="{{ route('customer.lines.answer', $number) }}" enctype="multipart/form-data" data-answer-form>@csrf<input type="hidden" name="line_form" value="answer"><input type="hidden" name="schedule_mode" value="anytime">
<fieldset><legend class="sr-only">نوع پاسخ‌گو</legend><div class="grid gap-3 sm:grid-cols-2">@foreach(['new'=>['یک شخص جدید','شماره داخلی را انتخاب کنید؛ رمز امن ساخته می‌شود.'],'existing'=>['تلفن موجود','یک داخلی از سازمان خود را انتخاب کنید.'],'team'=>['تیم پاسخ‌گویی','تماس به اعضای آمادهٔ تیم پیشنهاد می‌شود.'],'menu'=>['منوی صوتی موجود','یک منوی منتشرشده را انتخاب کنید.'],'create_team'=>['ساخت تیم جدید','چند تلفن را هم‌زمان زنگ بزنید.'],'create_menu'=>['ساخت منوی صوتی','پیام و مقصد کلیدها را همین‌جا تنظیم کنید.']] as $value=>[$label,$hint])<label class="flex cursor-pointer items-start gap-3 rounded-xl border border-slate-200 p-4 has-[:checked]:border-blue-500 has-[:checked]:bg-blue-50"><input class="mt-1" type="radio" name="answerer" value="{{ $value }}" @checked($answerer === $value)><span><strong class="block text-sm">{{ $label }}</strong><span class="mt-1 block text-xs leading-6 text-slate-500">{{ $hint }}</span></span></label>@endforeach</div></fieldset>
<div data-answer-fields="new" class="grid gap-4 sm:grid-cols-2"><div><label class="block text-sm font-bold" for="first-phone-name">نام شخص یا تلفن</label><input required id="first-phone-name" name="display_name" value="{{ old('line_form') === 'phone' ? '' : old('display_name') }}" maxlength="100" placeholder="مثلاً سارا، پذیرش یا فروش" class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3"></div>
@include('customer.lines.partials.extension-number', ['inputId' => 'first-extension', 'formName' => 'answer'])
<p class="text-xs leading-6 text-slate-500 sm:col-span-2">داخلی متعلق به سازمان شماست و با هر تلفن SIP سازگار استفاده می‌شود. رمز اتصال به‌صورت امن ساخته می‌شود.</p></div>
@foreach(['existing'=>['extension_id',$extensions->where('enabled', true),'تلفن'],'team'=>['queue_id',$queues,'تیم'],'menu'=>['menu_id',$menus,'منوی منتشرشده']] as $choice=>[$field,$items,$label])
<div data-answer-fields="{{ $choice }}"><label class="block text-sm font-bold" for="answer-{{ $field }}">انتخاب {{ $label }}</label><select id="answer-{{ $field }}" name="{{ $field }}" class="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3"><option value="">انتخاب کنید</option>@foreach($items as $item)<option value="{{ $item->id }}" @selected(old($field, $route?->destination_id) == $item->id)>{{ $choice === 'existing' ? ($item->display_name ?: 'داخلی '.$item->extension).' · '.$item->extension : $item->name }}</option>@endforeach</select>
@if($choice === 'team')<p class="mt-3 text-xs leading-7 text-slate-600">ابتدا برای همکاران، در بخش تلفن‌ها داخلی بسازید؛ سپس <a class="font-bold text-blue-700 underline" href="{{ route('teams.index') }}">تیم پاسخ‌گویی بسازید</a> و به این صفحه برگردید.</p>@elseif($choice === 'menu')<p class="mt-3 text-xs leading-7 text-slate-600"><a class="font-bold text-blue-700 underline" href="{{ route('ivr-menus.index') }}">ساخت منوی صوتی</a>: پیام خوش‌آمدگویی و مقصد کلیدها را مشخص کنید، منو را منتشر کنید و اینجا انتخاب کنید.</p>@elseif($items->isEmpty())<p class="mt-3 text-xs text-amber-800">هنوز تلفنی ندارید. گزینهٔ «یک شخص جدید» را انتخاب کنید.</p>@endif</div>
@endforeach
<div data-answer-fields="create_team" class="space-y-4">
<label class="block text-sm font-bold">نام تیم<input name="team_name" value="{{ old('team_name') }}" maxlength="100" class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3"></label>
<fieldset><legend class="text-sm font-bold">تلفن‌های پاسخ‌گوی تیم</legend>@foreach($extensions->where('enabled', true) as $phone)<label class="mt-2 flex min-h-11 items-center gap-3"><input type="checkbox" name="member_ids[]" value="{{ $phone->id }}" @checked(in_array($phone->id, old('member_ids', [])))>{{ $phone->display_name ?: $phone->extension }}</label>@endforeach</fieldset>
<label class="block text-sm font-bold">حداکثر انتظار (ثانیه)<input type="number" name="max_wait_seconds" min="10" max="600" value="{{ old('max_wait_seconds', 60) }}" class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3"></label>
<p class="text-xs leading-7 text-slate-600">اعضا باید در <a href="{{ route('availability.index') }}" class="font-bold text-blue-700 underline">وضعیت پاسخ‌گویی</a> آماده باشند. همگام‌سازی تیم تا یک دقیقه زمان می‌برد.</p>
</div>
<div data-answer-fields="create_menu" class="space-y-4">
<label class="block text-sm font-bold">نام منو<input name="menu_name" value="{{ old('menu_name') }}" maxlength="100" class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3"></label>
<label class="block text-sm font-bold">پیام خوش‌آمدگویی<input type="file" name="greeting" accept="audio/*" class="mt-2 block w-full text-sm"></label><p class="text-xs leading-7 text-slate-500">WAV، MP3 یا M4A تا ۱۰ مگابایت؛ پیام تا ۶۰ ثانیه استفاده می‌شود.</p>
@foreach(range(1, 3) as $digit)<fieldset class="rounded-xl border border-slate-200 p-4"><legend class="px-2 text-sm font-bold">کلید {{ $digit }}</legend><label class="block text-xs">عنوان<input name="choices[{{ $digit }}][label]" maxlength="60" value="{{ old('choices.'.$digit.'.label') }}" placeholder="مثلاً فروش" class="mt-2 w-full rounded-xl border border-slate-200 px-3 py-2"></label><label class="mt-3 block text-xs">مقصد<select name="choices[{{ $digit }}][destination]" class="mt-2 w-full rounded-xl border border-slate-200 bg-white px-3 py-2"><option value="">این کلید استفاده نشود</option>@foreach($extensions->where('enabled', true) as $phone)<option value="extension:{{ $phone->id }}" @selected(old('choices.'.$digit.'.destination') === 'extension:'.$phone->id)>{{ $phone->display_name ?: $phone->extension }}</option>@endforeach @foreach($queues as $team)<option value="queue:{{ $team->id }}" @selected(old('choices.'.$digit.'.destination') === 'queue:'.$team->id)>تیم {{ $team->name }}</option>@endforeach</select></label></fieldset>@endforeach
<label class="block text-sm font-bold">مقصد در صورت انتخاب‌نکردن کلید<select name="fallback" class="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3"><option value="">انتخاب کنید</option>@foreach($extensions->where('enabled', true) as $phone)<option value="extension:{{ $phone->id }}" @selected(old('fallback') === 'extension:'.$phone->id)>{{ $phone->display_name ?: $phone->extension }}</option>@endforeach @foreach($queues as $team)<option value="queue:{{ $team->id }}" @selected(old('fallback') === 'queue:'.$team->id)>تیم {{ $team->name }}</option>@endforeach</select></label>
</div>
<div class="rounded-xl bg-slate-50 p-4 text-sm leading-7"><span class="text-slate-500">مسیر فعلی:</span> <bdi dir="ltr">{{ $number->number }}</bdi> ← <strong>{{ $route?->destinationLabel() ?? 'هنوز انتخاب نشده' }}</strong></div>
<button class="commerce-button w-full sm:w-auto" data-busy-label="در حال ذخیره…">ذخیره پاسخ‌گو و ادامه</button>
</form></fieldset></section>
<section id="phones" class="panel scroll-mt-5 p-5 sm:p-7"><h2 class="text-lg font-black">۲. تلفن‌های سازمان را وصل کنید</h2><p class="mt-2 text-sm leading-7 text-slate-600">هر همکار یک داخلی اختصاصی دارد. برای اتصال، داخلی و نوع دستگاه را در راهنمای زیر انتخاب کنید.</p>
<div class="mt-5 space-y-3">@forelse($extensions as $extension)<article class="rounded-xl border border-slate-200 p-4"><div class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="text-sm font-bold">{{ $extension->display_name ?: 'تلفن' }} <bdi class="mr-2 text-slate-500" dir="ltr">{{ $extension->extension }}</bdi></h3><p class="mt-1 text-xs {{ $extension->enabled ? 'text-blue-700' : 'text-slate-500' }}">{{ $extension->enabled ? 'داخلی فعال · وضعیت اتصال را روی دستگاه بررسی کنید' : 'داخلی غیرفعال' }}</p></div><a class="min-h-11 inline-flex items-center text-sm font-bold text-blue-700" data-connect-phone="{{ $extension->extension }}" href="#phone-{{ $extension->id }}">اطلاعات اتصال ↓</a></div>
<details id="phone-{{ $extension->id }}" class="mt-3 rounded-xl bg-slate-50 p-4" @if(is_array($credentials) && ($credentials['extension'] ?? null) === $extension->extension) open @endif><summary class="cursor-pointer text-sm font-bold">اطلاعات اتصال و رمز تلفن</summary><dl class="mt-4 grid gap-3 text-sm sm:grid-cols-2">@foreach(['سرور' => config('voip.sip_host'), 'پورت' => config('voip.sip_port'), 'نام کاربری / شناسه احراز هویت' => $extension->extension, 'نوع اتصال' => 'SIP / UDP'] as $label => $value)<div><dt class="text-xs text-slate-500">{{ $label }}</dt><dd class="mt-1 flex items-center justify-between gap-2"><bdi class="break-all font-bold" dir="ltr">{{ $value }}</bdi>@if($label !== 'نوع اتصال')<button type="button" data-copy-value="{{ $value }}" aria-label="کپی {{ $label }}" class="min-h-11 shrink-0 px-2 text-xs font-bold text-blue-700">کپی</button>@endif</dd></div>@endforeach</dl>
@if(is_array($credentials) && ($credentials['extension'] ?? null) === $extension->extension)<div class="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-3"><p class="text-xs leading-6 text-amber-900">رمز فقط در این مرحله نمایش داده می‌شود؛ اکنون در جای امن نگه دارید.</p><div class="mt-2 flex flex-wrap items-center gap-2"><label class="sr-only" for="phone-password-{{ $extension->id }}">رمز اتصال داخلی {{ $extension->extension }}</label><input id="phone-password-{{ $extension->id }}" type="password" readonly autocomplete="off" value="{{ $credentials['password'] }}" class="min-w-0 flex-1 rounded-lg border border-amber-200 bg-white p-2 font-mono text-sm" dir="ltr"><button type="button" data-toggle-password="phone-password-{{ $extension->id }}" aria-controls="phone-password-{{ $extension->id }}" aria-pressed="false" class="min-h-11 px-2 text-xs font-bold text-blue-700">نمایش رمز</button><button type="button" data-copy-input="phone-password-{{ $extension->id }}" class="min-h-11 px-2 text-xs font-bold text-blue-700">کپی رمز</button></div></div>@else<p class="mt-3 text-xs leading-6 text-slate-600">رمز قبلی دوباره نمایش داده نمی‌شود. اگر آن را ندارید، رمز جدید بسازید و تنظیمات دستگاه را به‌روز کنید.</p>@endif
@if($canManage)<div class="mt-4 flex flex-wrap gap-3"><form method="POST" action="{{ route('customer.lines.phone.reset', [$number, $extension]) }}" onsubmit="return confirm('رمز قبلی از اعتبار خارج می‌شود و باید رمز جدید را در تلفن وارد کنید. ادامه می‌دهید؟')">@csrf<button class="min-h-11 rounded-xl border border-blue-200 bg-white px-4 text-xs font-bold text-blue-700">ساخت رمز جدید</button></form><form method="POST" action="{{ route('customer.lines.phone.update', [$number, $extension]) }}">@csrf @method('PUT')<input type="hidden" name="enabled" value="{{ $extension->enabled ? 0 : 1 }}"><button class="min-h-11 rounded-xl border border-slate-200 bg-white px-4 text-xs font-bold text-slate-700">{{ $extension->enabled ? 'غیرفعال‌کردن داخلی' : 'فعال‌کردن داخلی' }}</button></form></div>@endif</details></article>@empty<p class="rounded-xl bg-slate-50 p-4 text-sm leading-7 text-slate-600">هنوز تلفنی ساخته نشده است. برای شروع، در بخش بالا «یک شخص جدید» را انتخاب کنید.</p>@endforelse</div>
@if($canManage)<details class="mt-5 border-t border-slate-100 pt-5" @if(old('line_form') === 'phone') open @endif><summary class="cursor-pointer text-sm font-bold text-blue-700">+ افزودن تلفن برای همکار دیگر</summary><form class="mt-4 grid gap-4 sm:grid-cols-2" method="POST" action="{{ route('customer.lines.phones', $number) }}">@csrf<input type="hidden" name="line_form" value="phone"><label class="min-w-0"><span class="block text-sm font-bold">نام همکار یا تلفن</span><input required name="display_name" value="{{ old('line_form') === 'phone' ? old('display_name') : '' }}" maxlength="100" placeholder="مثلاً پذیرش" class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3"></label>
@include('customer.lines.partials.extension-number', ['inputId' => 'additional-extension', 'formName' => 'phone'])
<div class="sm:col-span-2"><button class="commerce-button">ساخت تلفن</button><p class="mt-2 text-xs leading-6 text-slate-500">ساخت داخلی، پاسخ‌گوی خط یا مجوز تماس خروجی را تغییر نمی‌دهد؛ آن‌ها را جداگانه انتخاب کنید.</p></div></form></details>@endif
@include('customer.lines.partials.phone-guide')
<p data-copy-status role="status" aria-live="polite" class="mt-3 text-xs leading-6 text-slate-600"></p>
</section>
<section id="check" class="panel scroll-mt-5 p-5 sm:p-7"><h2 class="text-lg font-black">۳. با یک تماس واقعی بررسی کنید</h2><ol class="mt-4 list-decimal space-y-3 pr-5 text-sm leading-8 text-slate-700"><li>با راهنمای دستگاه انتخاب‌شده، حساب SIP را تنظیم کنید و وضعیت «Registered» را روی دستگاه بررسی کنید.</li><li>از یک موبایل به <bdi dir="ltr">{{ $number->number }}</bdi> زنگ بزنید. بررسی کنید پاسخ‌گوی انتخاب‌شده اجرا شود و صدا در هر دو جهت شنیده شود.</li><li>اگر تماس خروجی فعال است، از تلفن متصل‌شده به یک شمارهٔ مجاز زنگ بزنید و نمایش شمارهٔ خط و صدای دوطرفه را بررسی کنید.</li></ol><p class="mt-4 rounded-xl bg-blue-50 p-4 text-xs leading-7 text-blue-900">این صفحه ثبت زندهٔ دستگاه یا موفقیت تماس را تأیید نمی‌کند. نتیجهٔ واقعی را روی دستگاه و با تماس آزمایشی بررسی کنید.</p>@if(auth()->user()->hasPermission('calls.view'))<a href="{{ route('calls.index') }}" class="commerce-link mt-4 inline-flex min-h-11 items-center text-sm font-bold">مشاهده گزارش تماس‌ها ←</a>@endif</section>
</div>
<aside class="space-y-5 xl:sticky xl:top-6"><section class="panel p-5"><h2 class="font-black">تماس خروجی</h2><p class="mt-2 text-xs leading-7 text-slate-600">داخلی‌های سازمان با شمارهٔ همین خط تماس می‌گیرند. مقصدها طبق مجوز خط محدود می‌شوند.</p><fieldset @disabled(!$canManage)><form class="mt-4" method="POST" action="{{ route('customer.lines.outbound', $number) }}">@csrf<input type="hidden" name="enabled" value="0"><label class="flex items-center gap-3 text-sm font-bold"><input type="checkbox" name="enabled" value="1" @checked(old('enabled', $outboundEnabled ?? $number->outbound_enabled))> تماس خروجی فعال باشد</label><fieldset class="mt-4"><legend class="text-xs font-bold">تلفن‌هایی که با این شماره تماس بگیرند</legend>@foreach($extensions->where('enabled', true) as $phone)<label class="mt-2 flex min-h-11 items-center gap-2 text-xs"><input type="checkbox" name="extension_ids[]" value="{{ $phone->id }}" @checked(in_array($phone->id, old('extension_ids', $extensions->filter(fn($item) => $item->outboundRoute?->sip_number_id === $number->id && $item->outboundRoute?->enabled)->modelKeys())))>{{ $phone->display_name ?: $phone->extension }}</label>@endforeach</fieldset><p class="mt-3 text-xs leading-7 text-slate-500">انتخاب تلفن، شماره تماس خروجی همان تلفن را به این خط تغییر می‌دهد.</p><button class="commerce-secondary mt-4 w-full">ذخیره تنظیم خروجی</button></form></fieldset></section><a href="{{ route('contact') }}" class="commerce-secondary w-full">کمک از پشتیبانی</a></aside>
</div></div>
@endsection
